-- migration_084 — timestamped first-party button clicks
--
-- migration_083 intentionally stores page traffic only as daily aggregates.
-- That is still the right shape for pageviews, but it cannot answer questions
-- such as "did anyone press Try 1 receipt in the last 10 hours?". Keep the
-- aggregate tables unchanged and add an event row only for synthetic /click/
-- paths. An event contains the action name and server timestamp—no IP, user
-- agent, visitor hash, user id, or request body.
--
-- Safe to re-run.

create table if not exists public.site_click_events (
  id         bigint generated by default as identity primary key,
  name       text        not null check (name ~ '^[a-z0-9-]{1,80}$'),
  clicked_at timestamptz not null default now()
);

create index if not exists site_click_events_clicked_at_idx
  on public.site_click_events (clicked_at desc);
create index if not exists site_click_events_name_clicked_at_idx
  on public.site_click_events (name, clicked_at desc);

alter table public.site_click_events enable row level security;
revoke all on table public.site_click_events from public, anon, authenticated;

-- Preserve migration_083's aggregate behavior and additionally timestamp
-- button clicks. Pageviews never enter the event table.
create or replace function public.record_visit(p_path text, p_visitor_hash text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  safe_path text := left(coalesce(p_path, '/'), 200);
  click_name text;
begin
  insert into public.site_visits (day, path, views)
  values (current_date, safe_path, 1)
  on conflict (day, path) do update set views = public.site_visits.views + 1;

  if p_visitor_hash is not null and length(p_visitor_hash) between 16 and 128 then
    insert into public.site_visitor_days (day, visitor_hash)
    values (current_date, p_visitor_hash)
    on conflict do nothing;
  end if;

  if safe_path like '/click/%' then
    click_name := substring(safe_path from 8);
    if click_name ~ '^[a-z0-9-]{1,80}$' then
      insert into public.site_click_events (name) values (click_name);
    end if;
  end if;
end
$$;

revoke all on function public.record_visit(text, text) from public, anon, authenticated;
grant execute on function public.record_visit(text, text) to service_role;

create or replace function public.site_click_events_since(p_hours int default 24)
returns table (click_name text, clicked_at timestamptz)
language sql
stable
security definer
set search_path = public
as $$
  select e.name, e.clicked_at
  from public.site_click_events e
  where e.clicked_at >= now() - make_interval(hours => greatest(p_hours, 1))
  order by e.clicked_at desc
  limit 5000
$$;

revoke all on function public.site_click_events_since(int) from public, anon, authenticated;
grant execute on function public.site_click_events_since(int) to service_role;
