// Curated emoji catalog used by the category picker on web + mobile.
// Grouped into sections so the picker has the same shape as a system emoji
// keyboard. searchEmoji(q) does a keyword lookup on a side table — so typing
// "starbucks" surfaces ☕ even though the literal text isn't present.
//
// Intentionally avoids flags, regional indicators, and skin-tone modifiers —
// they bloat the catalog and add nothing for category labelling.

export const EMOJI_SECTIONS = [
  {
    id: 'drinks',
    label: 'Drinks',
    emojis: ['☕','🍵','🥤','🧃','🥛','🧋','💧','🧊','🍶','🍹','🧉','🍺','🍻','🍷','🥂','🥃','🍸','🍾','🍼'],
  },
  {
    id: 'food',
    label: 'Food',
    emojis: ['🍎','🍌','🍇','🍊','🍓','🍑','🍍','🥝','🍒','🥭','🍉','🥥','🍈','🥦','🥕','🌽','🥒','🥬','🌶️','🍅','🥑','🍞','🥖','🥨','🥯','🧀','🥩','🍗','🍖','🥓','🍳','🥚','🥗','🥪','🌮','🌯','🥙','🍕','🍔','🍟','🍝','🍜','🍣','🍱','🥟','🍤'],
  },
  {
    id: 'sweets',
    label: 'Sweets',
    emojis: ['🍪','🎂','🍰','🧁','🍫','🍬','🍭','🍩','🍮','🍯','🍦','🍨','🥧'],
  },
  {
    id: 'home',
    label: 'Home',
    emojis: ['🏠','🛏️','🛋️','🪑','🚪','🪟','🚿','🛁','🚽','🧻','🧴','🪣','🧹','🧺','🧽','🧼','🪥','🪒','🧯','🪜','🔑','🪞','🛒'],
  },
  {
    id: 'tech',
    label: 'Tech',
    emojis: ['📱','💻','🖥️','⌨️','🖱️','🖨️','💾','💿','📀','🎧','🎤','📷','📸','📹','📺','📻','🔌','🔋','📡','💡','🎮','🕹️'],
  },
  {
    id: 'health',
    label: 'Health',
    emojis: ['💊','🩺','🦷','👓','🥽','🧘','🏋️','🚴','🏃','⚽','🏀','🏈','⚾','🎾','🏐','🏓','🏸','🥊','🥋','🩹','🧪','🌡️','🧬','💉','🧴'],
  },
  {
    id: 'pets',
    label: 'Pets',
    emojis: ['🐶','🐱','🐹','🐰','🐦','🐟','🐠','🐢','🦎','🦴','🐾','🐕','🐈','🐇','🐦','🦜','🦢'],
  },
  {
    id: 'travel',
    label: 'Travel',
    emojis: ['✈️','🚗','🚕','🚌','🚎','🏎️','🚓','🚑','🚒','🚐','🛻','🚛','🚜','🛵','🏍️','🚲','🛴','🚆','🚇','🚉','🚊','🚝','🚂','⛴️','🛳️','⛵','🚤','⚓','⛽','🏨','🛏️','🗺️','🧳','🛂','🛃'],
  },
  {
    id: 'work',
    label: 'Work',
    emojis: ['💼','📁','📂','📋','📌','📍','📎','🖇️','📏','📐','✂️','🖊️','🖋️','✏️','📝','📒','📓','📔','📕','📗','📘','📙','📚','📰','🗞️','🖼️','🎨','🖌️','🧮'],
  },
  {
    id: 'fun',
    label: 'Fun',
    emojis: ['🎬','🎮','🕹️','🎲','🧩','🎯','🎳','🎤','🎵','🎶','🎷','🎸','🎹','🥁','🎺','🎻','🪕','🎻','🎭','🎟️','🎫','🎪','🎨','📚','📖'],
  },
  {
    id: 'beauty',
    label: 'Beauty',
    emojis: ['💄','👄','💋','💅','🧴','🧼','🪥','🪒','💇','💆','🧖','👗','👘','👚','👕','👖','🩳','👔','👞','👟','👠','👡','👢','🥿','🩴','🧢','🎩','👑','💍','💎','👜','👛','👝','🎒'],
  },
  {
    id: 'money',
    label: 'Money',
    emojis: ['💰','💵','💴','💶','💷','💳','🏦','📈','📉','💸','🪙','🧾'],
  },
  {
    id: 'nature',
    label: 'Nature',
    emojis: ['🌳','🌲','🌴','🌵','🌿','☘️','🍀','🍁','🍂','🍃','🌱','🌷','🌹','🌺','🌻','🌼','🌸','💐','🪴','🌾','🌊','☀️','🌧️','⛈️','❄️','🔥','🌈'],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    emojis: ['📦','🎁','❤️','💚','💛','🧡','💙','💜','🖤','🤍','⭐','✨','✅','❌','❓','❗','🔁','🔄','🆕','🆙','🆓','🔒','🔓','📅','🗓️','⏰','⏱️','⏳','⌛','💡','🔥','🌱','🧩','🎉','🎊','🏆','🥇','🥈','🥉','🏅','🎖️'],
  },
]

// Side table — extra search keywords for emojis whose label isn't obvious.
// Lower-case substring match on these tags drives searchEmoji().
const EMOJI_TAGS = {
  '☕': ['coffee','latte','espresso','starbucks','dunkin','peets','mocha','americano','cappuccino','brew'],
  '🍵': ['tea','matcha','chai','oolong','earlgrey','green'],
  '🥤': ['soda','coke','pepsi','cola','pop','drink','fountain'],
  '🧃': ['juice','minutemaid','tropicana','box','oj'],
  '🥛': ['milk','milkshake','shake','dairy'],
  '🧋': ['boba','bubbletea','tapioca'],
  '💧': ['water','hydrate','aqua'],
  '🧊': ['ice','frozen','cube'],
  '🍶': ['sake','rice','wine'],
  '🍹': ['cocktail','tropical','tiki','margarita'],
  '🧉': ['mate','yerba'],
  '🍺': ['beer','ale','lager','pint','bar','pub'],
  '🍻': ['beer','cheers','bar','pub','toast'],
  '🍷': ['wine','red','merlot','cabernet','chardonnay','bar'],
  '🥂': ['champagne','toast','celebrate','bar'],
  '🥃': ['whiskey','whisky','bourbon','scotch','spirits','bar'],
  '🍸': ['martini','cocktail','bar'],
  '🍾': ['champagne','sparkling','bar','celebrate'],
  '🍼': ['baby','bottle','milk'],
  '🥑': ['avocado','guac','guacamole'],
  '🍎': ['apple','fruit'],
  '🍌': ['banana','fruit'],
  '🍓': ['strawberry','berry','fruit'],
  '🥦': ['broccoli','veggie','vegetable','green'],
  '🥕': ['carrot','veggie','vegetable'],
  '🌽': ['corn','vegetable'],
  '🍞': ['bread','loaf','bakery'],
  '🥖': ['baguette','bread','bakery'],
  '🥨': ['pretzel','snack'],
  '🥯': ['bagel','bakery'],
  '🧀': ['cheese','dairy'],
  '🥩': ['meat','steak','beef'],
  '🍗': ['chicken','meat','poultry','drumstick'],
  '🍖': ['meat','ribs','bbq'],
  '🥓': ['bacon','pork','meat'],
  '🍳': ['egg','breakfast','cook'],
  '🥚': ['egg'],
  '🥗': ['salad','healthy','veggie'],
  '🥪': ['sandwich','sub','deli'],
  '🌮': ['taco','mexican'],
  '🌯': ['burrito','wrap','mexican'],
  '🥙': ['pita','gyro','wrap'],
  '🍕': ['pizza','pie'],
  '🍔': ['burger','hamburger','fastfood'],
  '🍟': ['fries','frenchfries','fastfood'],
  '🍝': ['pasta','spaghetti','italian'],
  '🍜': ['ramen','noodle','soup'],
  '🍣': ['sushi','japanese'],
  '🍱': ['bento','lunch','japanese'],
  '🥟': ['dumpling','asian'],
  '🍤': ['shrimp','seafood','fried'],
  '🍪': ['cookie','sweet'],
  '🎂': ['cake','birthday','dessert'],
  '🍰': ['cake','dessert','slice'],
  '🧁': ['cupcake','dessert'],
  '🍫': ['chocolate','candy','dessert'],
  '🍬': ['candy','sweet'],
  '🍭': ['lollipop','candy'],
  '🍩': ['donut','doughnut','dessert','dunkin'],
  '🍮': ['pudding','flan','dessert'],
  '🍯': ['honey','sweet'],
  '🍦': ['icecream','dessert','softserve'],
  '🍨': ['icecream','sundae','dessert'],
  '🥧': ['pie','dessert'],
  '🏠': ['home','house','property'],
  '🛏️': ['bed','sleep','bedroom'],
  '🛋️': ['couch','sofa','livingroom'],
  '🪑': ['chair','furniture'],
  '🚪': ['door','entrance'],
  '🪟': ['window'],
  '🚿': ['shower','bathroom'],
  '🛁': ['bath','bathtub'],
  '🚽': ['toilet','bathroom'],
  '🧻': ['toilet','paper','tissue','household'],
  '🧴': ['lotion','soap','household','beauty'],
  '🪣': ['bucket','cleaning'],
  '🧹': ['broom','clean'],
  '🧺': ['laundry','basket'],
  '🧽': ['sponge','clean'],
  '🧼': ['soap','clean','hygiene'],
  '🪥': ['toothbrush','dental'],
  '🪒': ['razor','shave'],
  '🧯': ['extinguisher','fire'],
  '🪜': ['ladder','tools'],
  '🔑': ['key','lock'],
  '🪞': ['mirror'],
  '🛒': ['cart','shopping','grocery'],
  '📱': ['phone','mobile','cell','smartphone'],
  '💻': ['laptop','computer'],
  '🖥️': ['desktop','computer','monitor'],
  '⌨️': ['keyboard','typing'],
  '🖱️': ['mouse','computer'],
  '🖨️': ['printer','print','ink'],
  '💾': ['floppy','save','disk'],
  '🎧': ['headphones','audio','music'],
  '🎤': ['mic','microphone','karaoke'],
  '📷': ['camera','photo'],
  '📸': ['camera','flash','photo'],
  '📹': ['video','camcorder'],
  '📺': ['tv','television','stream'],
  '📻': ['radio','audio'],
  '🔌': ['plug','power','charge'],
  '🔋': ['battery','power'],
  '📡': ['antenna','internet','satellite'],
  '💡': ['lightbulb','idea','electric'],
  '🎮': ['gaming','console','controller'],
  '🕹️': ['joystick','gaming'],
  '💊': ['pill','medicine','pharmacy'],
  '🩺': ['stethoscope','medical','doctor'],
  '🦷': ['tooth','dental'],
  '👓': ['glasses','vision','optometry'],
  '🥽': ['goggles','vision'],
  '🧘': ['yoga','meditate','wellness'],
  '🏋️': ['gym','weights','fitness'],
  '🚴': ['bike','cycling','exercise'],
  '🏃': ['run','jog','exercise'],
  '🩹': ['bandage','firstaid'],
  '🧪': ['lab','test','science'],
  '🌡️': ['thermometer','temp','fever'],
  '🧬': ['dna','genetics','science'],
  '💉': ['syringe','vaccine','injection'],
  '🐶': ['dog','puppy','pet'],
  '🐱': ['cat','kitten','pet'],
  '🐹': ['hamster','pet','rodent'],
  '🐰': ['rabbit','bunny','pet'],
  '🐦': ['bird','pet'],
  '🐟': ['fish','pet','aquarium'],
  '🐢': ['turtle','tortoise','pet'],
  '🦎': ['lizard','reptile','pet'],
  '🦴': ['bone','dog','treat'],
  '🐾': ['paw','pet','animal'],
  '🐕': ['dog','pet'],
  '🐈': ['cat','pet'],
  '✈️': ['plane','flight','travel','airline'],
  '🚗': ['car','auto','drive'],
  '🚕': ['taxi','uber','lyft','rideshare'],
  '🚌': ['bus','transit'],
  '🏎️': ['racecar','sport'],
  '🚑': ['ambulance','medical'],
  '⛽': ['gas','fuel','petrol'],
  '🏨': ['hotel','lodging','stay'],
  '🗺️': ['map','travel'],
  '🧳': ['luggage','suitcase','travel'],
  '💼': ['briefcase','work','business'],
  '📋': ['clipboard','list','task'],
  '📎': ['paperclip','attach'],
  '🖊️': ['pen','write'],
  '✏️': ['pencil','write','draw'],
  '📝': ['memo','note','write'],
  '📚': ['books','library','study'],
  '🎬': ['movie','film','cinema'],
  '🎵': ['music','note'],
  '🎶': ['music','notes','song'],
  '🎯': ['target','aim','dart'],
  '🎲': ['dice','game','random'],
  '🧩': ['puzzle','piece'],
  '🎤': ['mic','karaoke','sing'],
  '💄': ['lipstick','makeup','beauty'],
  '💅': ['nails','manicure'],
  '👗': ['dress','clothing','fashion'],
  '👔': ['shirt','tie','formal'],
  '👞': ['shoe','formal'],
  '👟': ['sneaker','shoe','athletic'],
  '👠': ['heels','shoe'],
  '🧢': ['cap','hat','baseball'],
  '🎩': ['tophat','formal'],
  '👑': ['crown','royal'],
  '💍': ['ring','jewelry','wedding'],
  '💎': ['diamond','gem','jewelry'],
  '👜': ['handbag','purse'],
  '🎒': ['backpack','school'],
  '💰': ['money','cash','bag'],
  '💵': ['dollar','cash','money'],
  '💳': ['card','credit','debit'],
  '🏦': ['bank','finance'],
  '📈': ['chart','up','gain','stock'],
  '📉': ['chart','down','loss','stock'],
  '💸': ['money','spend','cash','fly'],
  '🪙': ['coin','crypto','money'],
  '🧾': ['receipt','bill'],
  '🌳': ['tree','outdoor','plant','garden'],
  '🌲': ['evergreen','tree','outdoor'],
  '🌴': ['palm','tree','tropical'],
  '🌵': ['cactus','desert','plant'],
  '🌿': ['herb','plant','green'],
  '🍀': ['clover','luck','green'],
  '🌱': ['seedling','grow','green','plant'],
  '🌷': ['tulip','flower'],
  '🌹': ['rose','flower'],
  '🌻': ['sunflower','flower'],
  '🌼': ['flower'],
  '💐': ['bouquet','flower','gift'],
  '🪴': ['potted','plant','houseplant'],
  '🌾': ['wheat','grain'],
  '🌊': ['wave','ocean','water'],
  '☀️': ['sun','sunny','weather'],
  '🌧️': ['rain','weather'],
  '❄️': ['snow','cold','winter'],
  '🔥': ['fire','hot','spicy'],
  '🌈': ['rainbow','pride'],
  '📦': ['box','package','shipping','default'],
  '🎁': ['gift','present','wrap','birthday'],
  '❤️': ['heart','love','red'],
  '⭐': ['star','favorite'],
  '✅': ['check','done','yes'],
  '❌': ['x','no','cancel'],
  '🔁': ['repeat','loop','recurring','subscription'],
  '🔒': ['lock','security','private'],
  '📅': ['calendar','date','schedule'],
  '⏰': ['clock','alarm','time'],
  '🏆': ['trophy','award','win'],
}

const ALL_EMOJIS = (() => {
  const seen = new Set()
  for (const s of EMOJI_SECTIONS) for (const e of s.emojis) seen.add(e)
  return [...seen]
})()

// Substring match on the emoji itself, the section label, or the tag list.
// Returns up to `limit` results, ranked: section-label match > tag match.
export function searchEmoji(query, limit = 64) {
  const q = (query || '').trim().toLowerCase()
  if (!q) return ALL_EMOJIS.slice(0, limit)

  const sectionHits = []
  for (const s of EMOJI_SECTIONS) {
    if (s.label.toLowerCase().includes(q) || s.id.includes(q)) {
      for (const e of s.emojis) sectionHits.push(e)
    }
  }
  const tagHits = []
  for (const [emoji, tags] of Object.entries(EMOJI_TAGS)) {
    if (tags.some(t => t.includes(q))) tagHits.push(emoji)
  }
  const merged = []
  const seen = new Set()
  for (const e of [...sectionHits, ...tagHits]) {
    if (!seen.has(e)) { merged.push(e); seen.add(e) }
    if (merged.length >= limit) break
  }
  return merged
}
