export const FEATURE_DETAILS = {
 capture: {
  income:{name:'Income and records',eyebrow:'Capture · Income',title:'Give your plan a reliable starting point.',summary:'Record income sources and payment timing so budgets and upcoming obligations begin with information you recognize.',actionHref:'/goals/first-budget.html',action:'Read the budget guide',screen:{src:'/marketing/current/budget.webp',width:1440,height:900,alt:'GetGuac Budget showing income, spending and money flow with demo data'},steps:[['Add','Income sources'],['Schedule','Expected timing'],['Review','Before planning']]},
  accounts:{name:'Accounts and documents',eyebrow:'Capture · Accounts',title:'Keep the balances and documents that complete the picture.',summary:'Add useful account, asset, debt and statement records without making a bank connection mandatory.',actionHref:'/bank',action:'Open statements',screen:{src:'/marketing/current/bank.webp',width:1148,height:718,alt:'GetGuac Bank workspace with statement upload and recorded fee and interest totals'}},
  email:{name:'Email and connections',eyebrow:'Capture · Email',title:'Bring digital shopping records into one private inbox.',summary:'Use your GetGuac address for supported shopping mail and route receipt emails for review while promotions remain separate from purchases.',actionHref:'/how-email-works',action:'Read the email guide',screen:{src:'/marketing/current/inbox.webp',width:1148,height:718,alt:'GetGuac Inbox workspace with message search and retailer connection controls'}},
  receipts:{name:'Receipt capture',eyebrow:'Capture · Receipts',title:'Turn each receipt into searchable purchase memory.',summary:'Scan paper receipts or add digital ones, review the store, date, items and total, then find the purchase when you need it.',actionHref:'/join?try=receipt',action:'Try one receipt free',screen:{src:'/marketing/current/receipts.webp',width:1440,height:900,alt:'GetGuac Receipts screen showing searchable itemized purchase records'}},
 },
 understand: {
  dashboard:{name:'Dashboard',eyebrow:'Understand · Dashboard',title:'Start with the signals that matter today.',summary:'Bring activity, reminders and useful money indicators into one starting view, with the underlying records close by.',actionHref:'/dashboard',action:'Open Dashboard',screen:{src:'/marketing/current/dashboard.webp',width:1148,height:718,alt:'GetGuac Dashboard showing spending, budget, cash flow and money indicators'}},
  budget:{name:'Budget',eyebrow:'Understand · Budget',title:'Plan the month, then compare it with reality.',summary:'Start with income and expected costs, assign the plan, and adjust it as your recorded activity changes.',actionHref:'/goals/first-budget.html',action:'Read the budget guide',screen:{src:'/marketing/current/budget.webp',width:1440,height:900,alt:'GetGuac Budget showing income, spending and money flow with demo data'},steps:[['Start','Income + bills'],['Plan','Spending + savings'],['Compare','Actual vs plan']]},
  reports:{name:'Reports and insights',eyebrow:'Understand · Reports',title:'See the items behind every spending pattern.',summary:'Move from a category or period total to the purchase records that shaped it, rather than stopping at a store total.',actionHref:'/reports',action:'Open Reports',screen:{src:'/marketing/current/reports.webp',width:1440,height:900,alt:'GetGuac category report showing spending amounts and proportional bars'}},
  'guac-ai':{name:'Guac AI',eyebrow:'Understand · Guac AI',title:'Ask a specific question about your saved records.',summary:'Use Guac AI to explore a store, category or period, then review the records supporting the answer before deciding.',actionHref:'/chat',action:'Open Guac AI',screen:{src:'/marketing/current/guac-ai.webp',width:1148,height:718,alt:'GetGuac AI chat workspace with suggested questions about saved money records'}},
 },
 protect: {
  goals:{name:'Savings and goals',eyebrow:'Protect · Goals',title:'Give what matters a target and a visible pace.',summary:'Set the purpose, amount and timeframe, record progress, and revisit the plan as life changes.',actionHref:'/goals/money-goals.html',action:'Read the goals guide',steps:[['Choose','Purpose + target'],['Record','Saved progress'],['Review','Pace + next step']]},
  bills:{name:'Bills and subscriptions',eyebrow:'Protect · Bills',title:'See recurring costs before they surprise the month.',summary:'Keep due dates and subscriptions visible so you can decide what still belongs in your budget.',actionHref:'/features/prepare',action:'Explore bill tracking',screen:{src:'/marketing/current/bills.webp',width:1440,height:900,alt:'GetGuac bills calendar showing recurring costs and due dates'}},
  returns:{name:'Returns and refunds',eyebrow:'Protect · Returns',title:'Keep the return deadline and refund status in sight.',summary:'Connect the purchase record, return window, refundable amount and refund progress so value does not disappear after checkout.',actionHref:'/goals/recover.html',action:'Track returns',screen:{src:'/marketing/current/returns.webp',width:1440,height:900,alt:'GetGuac Returns screen showing purchase deadlines and refund status'}},
 },
}

export const getFeatureDetail=(group,tool)=>FEATURE_DETAILS[group]?.[tool]
