import { Camera, FileSearch, Brain, ClipboardList, Tags, ShieldCheck, Star, RefreshCw } from 'lucide-react'

export const GETGUAC_STAGES = [
  { slug:'capture', name:'Capture', short:'Bring every purchase in', color:'#168A4B', soft:'#EAF6ED', Icon:Camera, hero:'Turn scattered receipts into one dependable money memory.', summary:'Photograph a paper receipt or add a digital one. GetGuac shows the merchant, items and total in the receipt record pictured here.', benefits:['Paper and digital receipts','Searchable merchant and item history','Store, date and total extraction'], web:'/marketing/current/receipts.webp', phone:'/home/goals/phone-receipts.webp', webAlt:'Receipt records with stores, dates, categories and totals on GetGuac web', phoneAlt:'The same searchable receipt list in the GetGuac mobile app', cta:'See receipt capture' },
  { slug:'understand', name:'Understand', short:'Connect categories to wealth', color:'#2563A8', soft:'#EDF5FF', Icon:FileSearch, hero:'See what your categories are doing to your wealth.', summary:'The category breakdown shows where receipt-level spending went, while Guacanomics connects those purchase patterns to the wider financial picture.', benefits:['Spending by category','Practical budgeting context','Purchase patterns connected to wealth'], web:'/marketing/current/reports.webp', phone:'/home/goals/phone-guacscore.webp', webAlt:'GetGuac spending-by-category breakdown for practical budgeting', phoneAlt:'GetGuac Guacanomics view showing how purchase patterns affect the financial picture', cta:'Explore category insights' },
  { slug:'remember', name:'Remember', short:'Keep an item history', color:'#6D4BC3', soft:'#F3EFFF', Icon:Brain, hero:'Remember what came home long after checkout.', summary:'The Stash screens pictured here keep purchased products, stores and receipt history together so an item is easy to find again.', benefits:['Searchable purchased-product history','Store and receipt context','One record for each saved item'], web:'/marketing/current/stash.webp', phone:'/home/goals/phone-stash.webp', webAlt:'GetGuac Stash showing saved purchased products on the web', phoneAlt:'The same saved-product Stash in the GetGuac mobile app', cta:'Explore your Stash' },
  { slug:'prepare', name:'Prepare', short:'See upcoming bills', color:'#A16207', soft:'#FFF7E6', Icon:ClipboardList, hero:'See what is due before the month gets away from you.', summary:'The bills screens pictured here put expected payment dates and recurring charges into a quick monthly calendar.', benefits:['Upcoming bill dates','Recurring amounts in one place','Monthly calendar view'], web:'/marketing/current/bills.webp', phone:'/home/goals/phone-bills.webp', webAlt:'GetGuac bills calendar showing upcoming payments on the web', phoneAlt:'The same upcoming bills in the GetGuac mobile app', cta:'Explore the bills calendar' },
  { slug:'shop-smart', name:'Shop Smart', short:'Compare current prices', color:'#C25D13', soft:'#FFF1E7', Icon:Tags, hero:'Check a current price before buying again.', summary:'The Steals screens pictured here compare products and current prices so a repeat purchase starts with useful evidence.', benefits:['Current product prices','Saved products ready to compare','Price research kept outside receipts'], web:'/marketing/current/steals.webp', phone:'/home/goals/phone-steals.webp', webAlt:'GetGuac Steals showing current product prices on the web', phoneAlt:'The same product-price comparisons in the GetGuac mobile app', cta:'Explore price comparisons' },
  { slug:'protect', name:'Protect', short:'Track returns and refunds', color:'#0F766E', soft:'#E9F8F5', Icon:ShieldCheck, hero:'Protect the money that can still come back.', summary:'The return screens pictured here keep each deadline, refundable value and refund status visible after checkout.', benefits:['Return deadlines','Refundable value','Returned and pending status'], web:'/marketing/current/returns.webp', phone:'/home/goals/phone-returns.webp', webAlt:'GetGuac return tracker showing deadlines and refundable value on the web', phoneAlt:'The same returns and refund status in the GetGuac mobile app', cta:'Explore return protection' },
  { slug:'worth-it', name:'Worth It', short:'Rate real purchases', color:'#A17300', soft:'#FFF9DD', Icon:Star, hero:'Remember which purchases earned another dollar.', summary:'The Worth It screens pictured here let you rate a real purchase and keep the result with its receipt history.', benefits:['Fast purchase rating','Rating tied to the purchase','Wins and regrets kept visible'], web:'/marketing/current/worth-it.webp', phone:'/home/goals/phone-worth-it.webp', webAlt:'GetGuac Worth It purchase rating on the web', phoneAlt:'The same Worth It purchase rating in the GetGuac mobile app', cta:'Rate a real purchase' },
  { slug:'next-trip', name:'Next Trip', short:'Plan your shopping list', color:'#168A4B', soft:'#ECF8EE', Icon:RefreshCw, hero:'Bring a clearer list on your next trip.', summary:'The Smashlist screens pictured here organize items to buy again, with quantities, store context and restock reminders.', benefits:['Items grouped into shopping categories','Quantities and store context','Restock reminders for repeat purchases'], web:'/marketing/current/shopping.webp', phone:'/home/goals/phone-smashlist.webp', webAlt:'GetGuac Smashlist with shopping categories, quantities and restock reminders on the web', phoneAlt:'GetGuac mobile Smashlist showing a milk restock item and shopping categories', cta:'Explore shopping lists' },
]

export function getStage(slug) { return GETGUAC_STAGES.find(stage => stage.slug === slug) }
export function adjacentStages(slug) {
  const index = GETGUAC_STAGES.findIndex(stage => stage.slug === slug)
  if (index < 0) return {}
  return { previous: GETGUAC_STAGES[(index - 1 + GETGUAC_STAGES.length) % GETGUAC_STAGES.length], next: GETGUAC_STAGES[(index + 1) % GETGUAC_STAGES.length] }
}
