// Single source of truth for the Guac Arcade catalog — the /games hub,
// each game page's rails, and the sitemap all read from here.
//
// Two kinds of game live in `GAMES`:
//   • OURS       — a hand-built canvas/DOM component with its own route.
//   • EXTERNAL   — carries `provider` + `embed`, runs in an iframe from a
//                  partner network, served by app/games/[slug]. Generated by
//                  scripts/sync-external-games.mjs into externalGames.json.
// Downstream code should branch on `isExternal(game)` rather than sniffing
// fields, and must not assume an external game can report a score: they're
// cross-origin, so there is no GuacMoney award and no leaderboard for them.
// g1/g2 are the cover-art gradient, `motifs` are the floating cover emoji,
// `cat` groups the hub rows: arcade | sports | classic | goal | puzzle.
// `bestKey` is the game's own localStorage key (best score / saved progress);
// the hub's "Pick up where you left off" row is driven by its presence.
import EXTERNAL_GAMES from './externalGames.json'
import { OWN_GAMES, gameIdFor } from './ownGames'

// A game we don't host. `provider` is the key into lib/gameProviders.PROVIDERS.
export const isExternal = (game) => Boolean(game?.provider)

// Re-exported so this stays the one import for catalog consumers. Import it
// from './ownGames' directly when you need ONLY our games — that path skips
// externalGames.json, which is ~416 KB and belongs nowhere near a bundle that
// isn't the arcade.
export { OWN_GAMES }

// Ours first — the hub's category rows and "more games" grids keep their
// hand-tuned order, and the partner catalog fills in behind it. That ordering
// is deliberate: our games are the ones that pay GuacMoney and score to the
// leaderboard, so they should never be buried under 80 guest titles.
export const GAMES = [...OWN_GAMES, ...EXTERNAL_GAMES]

export const EXTERNAL = EXTERNAL_GAMES
export const externalBySlug = (slug) =>
  EXTERNAL_GAMES.find((g) => g.href === `/games/${slug}`) || null

export const CATEGORIES = [
  { id: 'money', title: 'Your Money games', emoji: '🥑', blurb: 'Play against your own spending — real purchases, real categories, real time. Sign in and the games rebuild from your receipts.' },
  { id: 'racing', title: 'Racing & wheels', emoji: '🏎️', blurb: 'Climb hills, grab cash, don’t flip — physics driving with a money twist.' },
  { id: 'arcade', title: 'Arcade classics', emoji: '🕹️', blurb: 'Mazes, asteroids, slingshots, bubbles — the greats, free in your browser.' },
  { id: 'sports', title: 'Sports', emoji: '⚽', blurb: 'Penalties and free throws — quick-fire sports for a coffee break.' },
  { id: 'classic', title: 'Classic favorites', emoji: '🃏', blurb: 'Solitaire, minesweeper, snake, pong — the timeless desk games.' },
  { id: 'goal', title: 'Goal games', emoji: '🏁', blurb: 'Debt-free, dream house, college fund, retirement — play the goals you’re saving for.' },
  { id: 'puzzle', title: 'Puzzle, word & strategy', emoji: '🧩', blurb: 'Daily words, sudoku, match-3 and slow-burn strategy.' },
]

export const FEATURED_HREF = '/games/splurge'

// Hub hero: the featured 2×2 tile + these covers = "Jump into our most
// popular games". Hand-ordered, not data-driven (no analytics yet).
export const POPULAR_HREFS = [
  '/games/invaders', '/games/budget', '/games/penalty', '/games/muncher',
  '/games/solitaire', '/games/bubbles', '/games/snake', '/games/hoops',
]

// gameIdFor now lives in ./ownGames — it is a pure href→slug helper with no
// catalog dependency, and the dashboard's arcade launcher needs it without
// pulling externalGames.json in behind it. Re-exported so this stays the one
// import for existing callers.
export { gameIdFor }

// Games with a real gameplay screenshot in /public/game-shots/<slug>.jpg —
// the canvas action games (captured via scripts, Playwright). GameCover uses
// the shot as cover art; board/DOM games (solitaire, sudoku, whack, …) keep
// their illustrated gradient tile.
export const SHOT_SLUGS = new Set([
  'splurge', 'invaders', 'budget', 'fruit', 'fling', 'flappy', 'muncher', 'rocks', 'darts',
  'bubbles', 'penalty', 'hoops', 'pong', 'breaker', 'nestegg', 'house', 'tuition',
  'rope',
])
export const shotFor = (href) => {
  const slug = (href || '').split('/').pop()
  return SHOT_SLUGS.has(slug) ? `/game-shots/${slug}.jpg` : null
}
