// Academy-native lessons: Budgeting and cash flow (7) + Emergency fund and savings (4).
// Same shape as lib/academy.js NATIVE_LESSONS, with `extras` and `check` inline.
// Examples are arithmetic on labelled illustrative inputs; utility lessons follow
// the owner rule of usage tasks with no invented dollar savings.

const Q = (q, options, answer, why) => ({ q, options, answer, why })
const U = '2026-10-01'

export const BUDGET_LESSONS = [
  {
    slug: 'zero-based-budgeting', title: 'Zero-based budgeting: give every dollar a job', category: 'Budgeting', readMins: 6, updated: U,
    excerpt: 'Income minus every planned category equals zero. More upkeep than 50/30/20, but nothing is left to drift.',
    body: [
      'In a zero-based budget, you assign every dollar of take-home pay to a purpose before the month begins — bills, groceries, savings, debt, fun — until income minus the plan equals exactly zero. Zero does not mean spending everything. Savings and extra debt payments are jobs too.',
      { h: 'Why it works' },
      'Money with no assigned purpose tends to disappear into small purchases. Giving it a job in advance turns every spending decision into a choice between categories you already agreed on, rather than a guess about whether there is “enough left”.',
      { h: 'How to build one' },
      { list: ['Start with expected take-home pay for the month.', 'List fixed costs first: rent, insurance, minimum payments.', 'Add variable needs: groceries, fuel, utilities — from real receipts.', 'Assign savings and extra debt as their own lines.', 'Give the remainder to wants, or to a buffer, until the total hits zero.'] },
      { h: 'When reality disagrees' },
      'Overspend in one category and you move money from another — on purpose, the same day. That rebalancing is the method working, not failing. At month end, any money left in a category can roll forward or go to savings.',
      { h: 'Who it suits' },
      'Zero-based budgeting suits tight months, irregular income and people who like detail. If it feels like too much upkeep, a simpler split such as 50/30/20 may be easier to keep. Either works when the numbers come from your real month.',
    ],
    extras: {
      objectives: ['Assign every dollar of income to a category', 'Treat savings as a category, not a leftover', 'Rebalance categories when the month changes'],
      ideas: [
        { t: 'Zero means assigned, not spent', d: 'Savings and debt payments count as jobs.' },
        { t: 'Rebalancing is normal', d: 'Moving money between categories is the method working.' },
        { t: 'Plan before the month starts', d: 'Decisions made in advance are easier than decisions made at checkout.' },
      ],
      plan: [
        { t: 'Write expected income', d: 'Take-home, for this month.' },
        { t: 'Fill fixed costs', d: 'Rent, insurance, minimums.' },
        { t: 'Fill variable needs from receipts', d: 'Groceries, fuel, utilities.' },
        { t: 'Assign savings and debt', d: 'Before wants.' },
        { t: 'Balance to zero', d: 'Wants or a buffer take the rest.' },
      ],
      example: {
        title: 'A $3,500 month, balanced to zero', intro: 'Illustrative take-home pay and categories.',
        head: ['Category', 'Assigned', 'Left to assign'],
        rows: [['Income', '', '$3,500'], ['Rent and utilities', '$1,450', '$2,050'], ['Groceries and fuel', '$650', '$1,400'], ['Insurance and minimum payments', '$300', '$1,100'], ['Emergency fund', '$300', '$800'], ['Extra debt payment', '$200', '$600'], ['Wants and buffer', '$600', '$0']],
        takeaway: 'Every dollar has a job. If groceries run $50 over, $50 moves from wants — the plan stays at zero.',
      },
      mistakes: ['Forgetting irregular costs such as annual premiums', 'Leaving savings for whatever is left', 'Abandoning the plan instead of rebalancing'],
      exercise: 'Write next month’s income at the top of a page and assign it until the remainder is exactly zero.',
      apply: [{ href: '/features/understand/budget', label: 'Budget', d: 'Income, categories and planned savings.' }, { href: '/goals/first-budget.html', label: 'Guide: build your first budget', d: 'Start from a real month.' }],
    },
    check: {
      questions: [
        Q('In a zero-based budget, “zero” means…', ['You spend everything', 'Every dollar is assigned a purpose', 'You save nothing', 'Your balance is zero'], 1, 'Savings and debt payments are assigned jobs too.'),
        Q('You overspend on groceries. What does the method say?', ['Give up', 'Move money from another category now', 'Use a credit card', 'Ignore it'], 1, 'Rebalancing keeps the plan honest.'),
        Q('Where should savings appear?', ['Whatever is left at month end', 'As its own category, assigned early', 'Nowhere', 'Only in good months'], 1, 'Paying savings first protects it.'),
      ],
      puzzle: { q: 'Income $4,000. Assigned: rent $1,600, food $700, transport $300, insurance $200, savings $500. How much is left to assign?', answer: '$700', steps: '$1,600 + $700 + $300 + $200 + $500 = $3,300. $4,000 − $3,300 = $700.' },
    },
  },
  {
    slug: 'fixed-variable-discretionary', title: 'Fixed, variable and discretionary costs', category: 'Budgeting', readMins: 5, updated: U,
    excerpt: 'Sorting spending into three kinds shows which costs you can change this month and which need a bigger decision.',
    body: [
      'Not all spending can be changed the same way. Sorting costs into three kinds tells you where a quick adjustment is possible and where only a bigger decision will move the number.',
      { h: 'The three kinds' },
      { list: ['Fixed: the same every month and set by a contract — rent, insurance, loan payments, most subscriptions.', 'Variable: needed, but the amount changes — groceries, fuel, utilities.', 'Discretionary: choices — dining out, entertainment, hobbies, upgrades.'] },
      { h: 'What each kind responds to' },
      'Discretionary costs respond to this week’s choices. Variable costs respond to habits and planning, such as a shopping list or lower usage. Fixed costs only change through a decision: a new plan, a renegotiated rate, a different home. Those decisions are less frequent but often the largest.',
      { h: 'Grey areas' },
      'Some costs move between groups. A phone plan is fixed, but choosing the plan is discretionary. Groceries are variable, but premium brands inside them are discretionary. Sort by what you would actually change, not by a textbook label.',
      { h: 'Use it' },
      'Total each group for one real month. If discretionary costs are small but fixed costs are large, trimming treats will not fix the budget — reviewing a fixed cost will.',
    ],
    extras: {
      objectives: ['Sort spending into fixed, variable and discretionary', 'Know which lever moves each kind', 'Find the group where a change matters most'],
      ideas: [
        { t: 'Different costs, different levers', d: 'Choices, habits or decisions.' },
        { t: 'Fixed costs are quiet but large', d: 'One renegotiation can beat a month of small cuts.' },
        { t: 'Sort by what you would change', d: 'Not by a textbook label.' },
      ],
      plan: [
        { t: 'Take one month of spending', d: 'Receipts, bills and statements.' },
        { t: 'Tag each line F, V or D', d: 'Fixed, variable, discretionary.' },
        { t: 'Total each group', d: 'And its share of take-home pay.' },
        { t: 'Pick one lever', d: 'A fixed-cost review, a habit or a choice.' },
      ],
      example: {
        title: 'One month, three groups', intro: 'Illustrative spending of $3,200.',
        head: ['Group', 'Examples', 'Amount', 'Share'],
        rows: [['Fixed', 'Rent, insurance, phone, car loan', '$1,920', '60%'], ['Variable', 'Groceries, fuel, utilities', '$800', '25%'], ['Discretionary', 'Dining, streaming, hobbies', '$480', '15%'], ['Total', '', '$3,200', '100%']],
        takeaway: 'With 60% fixed, a review of the phone or insurance plan may move more than any treat-cutting.',
      },
      mistakes: ['Only ever cutting discretionary spending', 'Treating every fixed cost as permanent', 'Labelling everything a need'],
      exercise: 'Tag last month’s ten largest costs as fixed, variable or discretionary.',
      apply: [{ href: '/goals/understand.html', label: 'Understand where it went', d: 'Spending from receipts.' }, { href: '/goals/bills.html', label: 'Bills calendar', d: 'Your fixed costs in one view.' }],
    },
    check: {
      questions: [
        Q('Which is a variable cost?', ['Rent', 'Groceries', 'Car loan', 'Insurance premium'], 1, 'Needed, but the amount changes.'),
        Q('What usually changes a fixed cost?', ['Skipping a coffee', 'A decision such as switching plans', 'Nothing ever', 'A shopping list'], 1, 'Fixed costs move through contracts and decisions.'),
        Q('Dining out is…', ['Fixed', 'Variable', 'Discretionary', 'A tax'], 2, 'It is a choice you can change this week.'),
      ],
      puzzle: { q: 'Fixed $2,100, variable $700, discretionary $350. What share of the $3,150 total is fixed?', answer: 'About 67%', steps: '$2,100 ÷ $3,150 = 0.667, about 67%.' },
    },
  },
  {
    slug: 'irregular-income-budget', title: 'Budgeting on irregular income', category: 'Budgeting', readMins: 6, updated: U,
    excerpt: 'Freelance, gig or commission pay? Plan on your lean month, park the extra and pay yourself a steady salary.',
    body: [
      'When income changes month to month, a budget built on an average fails in every below-average month. The fix is to plan on a lean month and use good months to protect the lean ones.',
      { h: 'Find your baseline' },
      'Look at the last 12 months of take-home income and note the lowest typical month — ignore a one-off disaster, but do not use the average. That baseline is what your essential budget must fit inside.',
      { h: 'The holding-account method' },
      { list: ['All income lands in one holding account.', 'Each month you pay yourself a fixed “salary” from it, equal to your baseline.', 'Extra in good months stays in the holding account as a buffer.', 'Once the buffer covers a few lean months, extra goes to goals.'] },
      { h: 'Set aside tax first' },
      'If tax is not withheld — common for freelancers — set a percentage of every payment aside before anything else, in a separate account. The right percentage depends on your situation; a tax professional or the IRS estimated-tax guidance can help you set it.',
      { h: 'Order of priorities in a good month' },
      'Tax set-aside, then the buffer, then the emergency fund, then goals. A lean month after a good one should feel boring, not frightening.',
    ],
    extras: {
      objectives: ['Find a lean-month baseline', 'Pay yourself a steady salary from a holding account', 'Set tax aside from every payment'],
      ideas: [
        { t: 'Plan on the lean month', d: 'Averages fail half the time.' },
        { t: 'Smooth income yourself', d: 'A holding account turns lumpy pay into a steady salary.' },
        { t: 'Tax money is not yours', d: 'Move it out the day you are paid.' },
      ],
      plan: [
        { t: 'List 12 months of income', d: 'Take-home amounts.' },
        { t: 'Pick the lean-month baseline', d: 'Lowest typical month.' },
        { t: 'Open a holding account', d: 'All income lands there.' },
        { t: 'Pay a fixed salary monthly', d: 'Equal to the baseline.' },
        { t: 'Grow a buffer first', d: 'Then goals.' },
      ],
      example: {
        title: 'Smoothing six uneven months', intro: 'Illustrative income with a $3,000 monthly salary paid from a holding account.',
        head: ['Month', 'Income', 'Salary paid', 'Holding balance'],
        rows: [['Start', '', '', '$2,000'], ['1', '$4,200', '$3,000', '$3,200'], ['2', '$2,400', '$3,000', '$2,600'], ['3', '$3,600', '$3,000', '$3,200'], ['4', '$2,100', '$3,000', '$2,300'], ['5', '$5,000', '$3,000', '$4,300'], ['6', '$2,700', '$3,000', '$4,000']],
        takeaway: 'Income swung from $2,100 to $5,000, but the household lived on a steady $3,000 and the buffer grew by $2,000.',
      },
      mistakes: ['Budgeting on the average month', 'Spending a good month as if it will repeat', 'Leaving tax money in the spending account'],
      exercise: 'Find your lowest typical month of income in the past year and write it down as your baseline salary.',
      apply: [{ href: '/features/understand/budget', label: 'Budget', d: 'Track income sources.' }, { href: '/goals/tax-records.html', label: 'Guide: tax-ready records', d: 'Business receipts as you go.' }],
    },
    check: {
      questions: [
        Q('Which income figure should your essentials fit inside?', ['Best month', 'Average month', 'Lean typical month', 'Annual total'], 2, 'Planning on the lean month keeps every month covered.'),
        Q('What does the holding account do?', ['Earns stock returns', 'Smooths lumpy income into a steady salary', 'Pays taxes automatically', 'Nothing'], 1, 'Income lands there; a fixed salary leaves it.'),
        Q('In a good month, what comes first?', ['A treat', 'Tax set-aside', 'New gadget', 'Investing everything'], 1, 'Tax money is owed, not spare.'),
      ],
      puzzle: { q: 'Holding balance $1,500. Income: $3,800 then $2,200. Salary $3,000 each month. What is the balance after two months?', answer: '$1,500', steps: '$1,500 + $3,800 − $3,000 = $2,300. $2,300 + $2,200 − $3,000 = $1,500.' },
    },
  },
  {
    slug: 'impulse-purchases', title: 'Impulse purchases: spot the trigger, add a pause', category: 'Budgeting', readMins: 5, updated: U,
    excerpt: 'Most impulse buys follow a pattern — a mood, a place, a notification. A short pause breaks it without banning anything.',
    body: [
      'Impulse purchases are rarely random. They tend to follow triggers: boredom, stress, a sale countdown, a saved card, a late-night scroll. Knowing your triggers is more useful than willpower.',
      { h: 'Common triggers' },
      { list: ['Emotion: tired, stressed, bored or celebrating.', 'Urgency: countdown timers and “only 2 left”.', 'Ease: saved cards and one-click checkout.', 'Place: certain stores, apps or times of day.'] },
      { h: 'The pause rule' },
      'For anything unplanned above a set amount, wait — overnight for small items, a few days for larger ones. If you still want it, buy it without guilt. Many wants fade once the trigger passes; the ones that remain were probably worth it.',
      { h: 'Add friction where it helps' },
      'Remove saved cards from shopping apps, unsubscribe from sale emails, and turn off shopping notifications. Each small step adds a moment to think.',
      { h: 'Learn from the receipt' },
      'Rate impulse purchases a week later: worth it or regret? Patterns in the regrets point to the triggers worth managing.',
    ],
    extras: {
      objectives: ['Name your impulse triggers', 'Use a pause rule with a set amount', 'Add friction to the easiest spending'],
      ideas: [
        { t: 'Triggers beat willpower', d: 'Change the situation, not just the decision.' },
        { t: 'A pause is not a ban', d: 'Buy it later if you still want it.' },
        { t: 'Urgency is designed', d: 'Countdown timers are there to stop you thinking.' },
      ],
      plan: [
        { t: 'Review last month’s unplanned buys', d: 'Note time, place and mood.' },
        { t: 'Set your pause amount', d: 'For example, anything over $30.' },
        { t: 'Remove saved cards', d: 'From apps you overuse.' },
        { t: 'Rate buys a week later', d: 'Worth it or regret.' },
      ],
      example: {
        title: 'A month of unplanned purchases, reviewed', intro: 'Illustrative purchases rated a week later.',
        head: ['Purchase', 'Trigger', 'Amount', 'A week later'],
        rows: [['Headphones', 'Flash sale timer', '$59', 'Regret'], ['Takeout', 'Tired after work', '$32', 'Worth it'], ['Shirt', 'Late-night scrolling', '$28', 'Regret'], ['Board game', 'Celebrating', '$40', 'Worth it'], ['Regret total', '', '$87', '']],
        takeaway: 'The regrets share a trigger — screens and urgency — so that is where friction helps, not the takeout.',
      },
      mistakes: ['Banning all unplanned spending', 'Keeping one-click checkout everywhere', 'Judging purchases only at the moment of buying'],
      exercise: 'Pick one shopping app and remove your saved card from it today.',
      apply: [{ href: '/goals/learn.html', label: 'Worth-It ratings', d: 'Rate purchases after the fact.' }],
    },
    check: {
      questions: [
        Q('What is a common impulse trigger?', ['A shopping list', 'A countdown timer', 'A monthly budget', 'A receipt'], 1, 'Urgency is designed to rush the decision.'),
        Q('What does the pause rule do?', ['Bans purchases', 'Delays unplanned buys above a set amount', 'Cancels cards', 'Doubles prices'], 1, 'Wants that survive the pause are often worth it.'),
        Q('Which adds helpful friction?', ['Saving more cards', 'Removing saved cards from apps', 'Turning on sale alerts', 'One-click checkout'], 1, 'A small extra step creates time to think.'),
      ],
      puzzle: { q: 'You regret about $90 of impulse buys a month. If a pause rule stops two-thirds of them, how much stays with you per year?', answer: '$720', steps: '$90 × 2/3 = $60 a month. $60 × 12 = $720.' },
    },
  },
  {
    slug: 'lifestyle-inflation', title: 'Lifestyle inflation: keep the raise', category: 'Budgeting', readMins: 5, updated: U,
    excerpt: 'Spending tends to rise to meet income. Decide where a raise goes before it arrives.',
    body: [
      'Lifestyle inflation — or lifestyle creep — is when spending rises with every pay rise, so a higher income leaves you no better off. It happens gradually: a nicer car, more takeout, upgraded subscriptions, each reasonable on its own.',
      { h: 'Why it is hard to notice' },
      'People adapt quickly to improvements, so last year’s upgrade soon feels normal. The new baseline then needs another raise to feel comfortable.',
      { h: 'Split the raise in advance' },
      'Before a raise or bonus arrives, decide its split. A common approach is to send at least half to savings, debt or investing and enjoy the rest. You still feel the improvement, and your future self gets a share.',
      { h: 'Automate the saved half' },
      'Raise your automatic savings or retirement contribution the same week the raise starts. Money that never reaches your spending account is not missed.',
      { h: 'Upgrade on purpose' },
      'Lifestyle upgrades are not bad. The difference is choosing them deliberately — one meaningful upgrade instead of many small ones you barely notice.',
    ],
    extras: {
      objectives: ['Recognise lifestyle creep', 'Split a raise before it arrives', 'Automate the saved portion'],
      ideas: [
        { t: 'You adapt quickly', d: 'Upgrades become the new normal within months.' },
        { t: 'Decide before the money lands', d: 'It is easier to save money you never saw.' },
        { t: 'One deliberate upgrade', d: 'Beats many unnoticed ones.' },
      ],
      plan: [
        { t: 'Note your next raise date', d: 'Or expected bonus.' },
        { t: 'Choose the split', d: 'For example, half saved.' },
        { t: 'Raise automatic transfers', d: 'The week it starts.' },
        { t: 'Pick one upgrade', d: 'And enjoy it fully.' },
      ],
      example: {
        title: 'A $300 monthly raise, split in half', intro: 'Illustrative after-tax raise.',
        head: ['Where it goes', 'Per month', 'Per year'],
        rows: [['Retirement or savings', '$150', '$1,800'], ['Enjoy now', '$150', '$1,800'], ['Total raise', '$300', '$3,600']],
        takeaway: 'You live $150 a month better and still add $1,800 a year to your future.',
      },
      mistakes: ['Upgrading everything at once', 'Deciding after the money is already spent', 'Treating every raise as permanent spending room'],
      exercise: 'Write down what percentage of your next raise you will save, and set the reminder to change your transfer.',
      apply: [{ href: '/calculators#retirement', label: 'Retirement calculator', d: 'See a higher contribution rate.' }, { href: '/goals/understand.html', label: 'Spending trends', d: 'Spot creep in your categories.' }],
    },
    check: {
      questions: [
        Q('Lifestyle inflation is…', ['Prices rising in shops', 'Spending rising with income', 'A tax', 'A savings account'], 1, 'Higher pay, higher spending, no progress.'),
        Q('When should you decide how to split a raise?', ['After spending it', 'Before it arrives', 'Never', 'At year end'], 1, 'Money you never see is easier to save.'),
        Q('Is upgrading your lifestyle always bad?', ['Yes', 'No — choosing upgrades deliberately is fine', 'Only cars', 'Only food'], 1, 'The problem is unnoticed creep, not enjoyment.'),
      ],
      puzzle: { q: 'A $4,800 yearly after-tax raise. You save 60%. How much per month goes to savings?', answer: '$240', steps: '$4,800 × 0.6 = $2,880 a year. ÷ 12 = $240.' },
    },
  },
  {
    slug: 'monthly-money-date', title: 'The monthly money date', category: 'Budgeting', readMins: 5, updated: U,
    excerpt: 'One short, regular review keeps a budget alive. Here is a simple agenda for it.',
    body: [
      'Budgets fail more often from neglect than from bad numbers. A regular, short review — a “money date”, alone or with a partner — catches drift while it is still easy to fix.',
      { h: 'A simple agenda' },
      { list: ['Look back: what did we spend in each category versus the plan?', 'Check bills: anything new, higher or due soon?', 'Check goals: are savings and debt on track?', 'Look ahead: any irregular costs next month?', 'Decide one change for next month.'] },
      { h: 'Keep it short and kind' },
      'The point is information, not blame. Start with what went well, keep it to a fixed time, and end with one decision rather than a list of resolutions.',
      { h: 'Doing it as a couple' },
      'Agree in advance on an amount each person can spend without discussion. That keeps the date about shared goals rather than individual purchases.',
      { h: 'Make it easy to start' },
      'Put it in the calendar on the same day each month, have the numbers ready before you sit down, and pair it with something you enjoy.',
    ],
    extras: {
      objectives: ['Run a short monthly review with a fixed agenda', 'End each review with one decision', 'Make money talks blame-free'],
      ideas: [
        { t: 'Neglect kills budgets', d: 'Regular review catches drift early.' },
        { t: 'One decision per month', d: 'Not a list of resolutions.' },
        { t: 'Personal spending money', d: 'Keeps couples’ reviews about shared goals.' },
      ],
      plan: [
        { t: 'Pick a recurring date', d: 'Same day each month.' },
        { t: 'Prepare the numbers', d: 'Category totals and upcoming bills.' },
        { t: 'Follow the agenda', d: 'Back, bills, goals, ahead.' },
        { t: 'Choose one change', d: 'Write it down.' },
      ],
      example: {
        title: 'One month’s review, at a glance', intro: 'Illustrative category totals against plan.',
        head: ['Category', 'Plan', 'Actual', 'Difference'],
        rows: [['Groceries', '$600', '$655', '+$55'], ['Dining out', '$200', '$170', '−$30'], ['Transport', '$250', '$240', '−$10'], ['Total', '$1,050', '$1,065', '+$15']],
        takeaway: 'Nearly on plan. The one decision: plan meals for the two busiest weeknights to bring groceries back.',
      },
      mistakes: ['Skipping months when they went badly', 'Turning the review into blame', 'Leaving with ten resolutions'],
      exercise: 'Add a recurring 30-minute money date to your calendar this month.',
      apply: [{ href: '/goals/reports.html', label: 'Reports', d: 'Monthly totals ready to review.' }, { href: '/goals/bills.html', label: 'Bills calendar', d: 'What is due next month.' }],
    },
    check: {
      questions: [
        Q('Why do budgets usually fail?', ['Bad maths', 'Neglect', 'Too many categories', 'Banks'], 1, 'A regular review prevents drift.'),
        Q('How should a money date end?', ['With blame', 'With one decision for next month', 'With ten goals', 'With a purchase'], 1, 'One change is easier to keep.'),
        Q('What helps couples keep reviews calm?', ['Reviewing every coffee', 'A personal amount each can spend without discussion', 'Skipping reviews', 'One person decides all'], 1, 'It keeps the focus on shared goals.'),
      ],
      puzzle: { q: 'Plan: food $500, fun $200, transport $150. Actual: $540, $160, $150. Over or under in total, and by how much?', answer: '$0 — exactly on plan', steps: 'Plan $850. Actual $540 + $160 + $150 = $850. Food was $40 over, fun $40 under.' },
    },
  },
  {
    slug: 'utility-bills-usage', title: 'Read your utility bills and lower usage', category: 'Budgeting', readMins: 5, updated: U,
    excerpt: 'Electricity and water bills are usage times rate plus fixed charges. Know the parts, then work on usage.',
    body: [
      'Utility bills look complicated, but most have the same parts: a fixed charge you pay regardless of use, a usage charge (units used × rate), and taxes or fees. Understanding the parts shows what you can and cannot change.',
      { h: 'Find the units' },
      'Electricity is usually billed in kilowatt-hours (kWh), gas in therms or cubic feet, and water in gallons or cubic feet. Compare units used with the same month last year — weather changes usage a lot, so month-to-month comparisons can mislead.',
      { h: 'What you can change' },
      { list: ['Heating and cooling settings, which are often the largest use.', 'Water heater temperature and hot-water use.', 'Devices left on standby and lights in empty rooms.', 'Leaks: a running toilet or dripping tap.'] },
      { h: 'What you usually cannot change' },
      'The fixed charge and the rate are set by the provider or regulator in many areas. Some regions let you choose a supplier or a time-of-use plan; check what applies where you live before switching anything.',
      { h: 'Track the result in units' },
      'Measure progress by units used, compared with the same month last year. Rates and weather change, so the dollar total alone does not show whether your habits worked.',
    ],
    extras: {
      objectives: ['Identify fixed, usage and tax charges on a bill', 'Compare usage with the same month last year', 'Choose usage tasks you control'],
      ideas: [
        { t: 'Usage × rate + fixed charges', d: 'The structure of most utility bills.' },
        { t: 'Compare like with like', d: 'Same month last year, in units.' },
        { t: 'Change what you control', d: 'Usage habits, not regulated rates.' },
      ],
      plan: [
        { t: 'Find three numbers on the bill', d: 'Units used, rate, fixed charge.' },
        { t: 'Compare with last year', d: 'Same month, in units.' },
        { t: 'Pick two usage tasks', d: 'Thermostat, leaks, standby.' },
        { t: 'Recheck next bill', d: 'Units, not just dollars.' },
      ],
      example: {
        title: 'Reading one electricity bill', intro: 'Illustrative bill: 620 kWh at $0.15 per kWh.',
        head: ['Line', 'Calculation', 'Amount'],
        rows: [['Fixed service charge', 'Set by the provider', '$12.00'], ['Usage charge', '620 kWh × $0.15', '$93.00'], ['Taxes and fees', 'As listed', '$7.00'], ['Total', '', '$112.00']],
        takeaway: 'Only the usage line responds to your habits. Track kWh next year, not just the total.',
      },
      mistakes: ['Comparing a winter bill with a summer bill', 'Judging progress by dollars when rates changed', 'Switching supplier without reading the terms'],
      exercise: 'Find the units used on your latest electricity bill and the same month last year.',
      apply: [{ href: '/goals/bills.html', label: 'Bills calendar', d: 'Utilities alongside other bills.' }],
    },
    check: {
      questions: [
        Q('Which part of a utility bill responds to your habits?', ['Fixed charge', 'Usage charge', 'Regulated rate', 'Account number'], 1, 'Units used × rate.'),
        Q('Best comparison for usage?', ['Last month', 'Same month last year', 'A neighbour', 'National average'], 1, 'Weather drives seasonal usage.'),
        Q('Electricity is usually billed in…', ['Gallons', 'Kilowatt-hours', 'Therms', 'Liters'], 1, 'kWh.'),
      ],
      puzzle: { q: 'A bill has a $10 fixed charge, 500 kWh at $0.18 and $6 of fees. What is the total?', answer: '$106', steps: '500 × $0.18 = $90. $10 + $90 + $6 = $106.' },
    },
  },
]

export const SAFETY_LESSONS = [
  {
    slug: 'tiered-cash-reserves', title: 'Tiered cash reserves: spending, buffer, emergency', category: 'Saving', readMins: 5, updated: U,
    excerpt: 'Three layers of cash — each with a job — stop small surprises from touching your emergency fund.',
    body: [
      'Keeping all your cash in one place blurs its purpose. A tiered approach gives each layer one job, so you always know which money is safe to spend.',
      { h: 'The three tiers' },
      { list: ['Tier 1 — spending account: this month’s bills and planned spending.', 'Tier 2 — buffer: a small cushion, often a few hundred dollars to one month of costs, for timing gaps and small surprises.', 'Tier 3 — emergency fund: months of essential expenses for real emergencies, kept separate and harder to reach.'] },
      { h: 'Why a buffer helps' },
      'Most surprises are small: a bill a few days before payday, a higher-than-usual grocery week. A buffer absorbs them so you do not overdraw checking or dip into the emergency fund for something minor.',
      { h: 'Where to keep each tier' },
      'Spending money in checking. The buffer can sit in checking or linked savings. The emergency fund belongs in a separate, insured savings account — reachable within a day or two but not attached to your debit card.',
      { h: 'Refill in order' },
      'If you use the buffer, refill it from next month’s budget. If you use the emergency fund, rebuilding it becomes the next priority goal.',
    ],
    extras: {
      objectives: ['Give each cash layer one job', 'Size a buffer for small surprises', 'Keep the emergency fund at arm’s length'],
      ideas: [
        { t: 'Purpose prevents misuse', d: 'Labelled money is harder to spend by accident.' },
        { t: 'Most surprises are small', d: 'A buffer handles them.' },
        { t: 'Distance protects the emergency fund', d: 'Separate account, not on your card.' },
      ],
      plan: [
        { t: 'Set the spending amount', d: 'This month’s plan.' },
        { t: 'Build a buffer', d: 'Start with a few hundred dollars.' },
        { t: 'Separate the emergency fund', d: 'Insured savings, different bank if helpful.' },
        { t: 'Refill in order', d: 'Buffer first from the next budget.' },
      ],
      example: {
        title: 'Three tiers for a household with $2,500 monthly essentials', intro: 'Illustrative amounts.',
        head: ['Tier', 'Job', 'Target'],
        rows: [['Spending', 'This month’s plan', 'One month of planned spending'], ['Buffer', 'Small surprises and timing gaps', '$500'], ['Emergency fund', 'Job loss, urgent repairs, medical', '$7,500 (3 months)']],
        takeaway: '$2,500 × 3 = $7,500. The $500 buffer keeps small surprises away from it.',
      },
      mistakes: ['One account for everything', 'No buffer, so every surprise hits the emergency fund', 'Linking the emergency fund to a debit card'],
      exercise: 'Name your three tiers and write the target for each.',
      apply: [{ href: '/goals/emergency.html', label: 'Guide: fund the cushion', d: 'Build tier 3.' }, { href: '/calculators#emergency', label: 'Emergency fund calculator', d: 'Size tier 3.' }],
    },
    check: {
      questions: [
        Q('What is the buffer for?', ['Long-term investing', 'Small surprises and timing gaps', 'Vacations', 'Retirement'], 1, 'It protects checking and the emergency fund.'),
        Q('Where should the emergency fund sit?', ['On your debit card', 'In a separate insured savings account', 'In stocks', 'In cash at home'], 1, 'Reachable, but at arm’s length.'),
        Q('You used the buffer. What next?', ['Ignore it', 'Refill it from next month’s budget', 'Close it', 'Borrow'], 1, 'Refill in order.'),
      ],
      puzzle: { q: 'Essentials are $3,100 a month. You want a 4-month emergency fund and a $600 buffer. Total reserves?', answer: '$13,000', steps: '$3,100 × 4 = $12,400. + $600 = $13,000.' },
    },
  },
  {
    slug: 'what-counts-as-emergency', title: 'What counts as an emergency?', category: 'Saving', readMins: 4, updated: U,
    excerpt: 'Decide in advance what the fund is for — it is the simplest way to stop it quietly becoming spending money.',
    body: [
      'An emergency fund only works if it is still there when a real emergency arrives. The easiest protection is a short written definition, made before you need it.',
      { h: 'The three-question test' },
      { list: ['Is it unexpected? A known annual bill is not.', 'Is it necessary? You would face real harm or cost without it.', 'Is it urgent? It cannot wait until you save separately.'] },
      'If the answer to all three is yes, it is an emergency. Job loss, urgent medical costs, a car repair you need for work and an essential home repair usually pass. A sale, a holiday or a planned purchase do not.',
      { h: 'Grey areas' },
      'A replacement phone may pass if you need it for work and it broke unexpectedly; an upgrade does not. When unsure, cover the minimum version of the need from the fund and pay for any upgrade separately.',
      { h: 'Write it down' },
      'List two or three things that qualify for your household. Couples should agree on the list together, so a withdrawal is never a surprise to either person.',
    ],
    extras: {
      objectives: ['Apply the unexpected, necessary, urgent test', 'Handle grey areas with the minimum-need rule', 'Agree a written definition'],
      ideas: [
        { t: 'Decide before the moment', d: 'Rules made calmly hold under pressure.' },
        { t: 'All three must be true', d: 'Unexpected, necessary and urgent.' },
        { t: 'Cover the minimum need', d: 'Upgrades are paid separately.' },
      ],
      plan: [
        { t: 'Write the three questions', d: 'Keep them with the account details.' },
        { t: 'List what qualifies', d: 'Two or three examples.' },
        { t: 'Agree as a household', d: 'Both partners sign off.' },
        { t: 'Move predictable costs out', d: 'Into sinking funds.' },
      ],
      example: {
        title: 'Five requests, tested', intro: 'Applying unexpected / necessary / urgent.',
        head: ['Request', 'Unexpected', 'Necessary', 'Urgent', 'Emergency?'],
        rows: [['Car transmission fails; needed for work', 'Yes', 'Yes', 'Yes', 'Yes'], ['Annual car insurance premium', 'No', 'Yes', 'Yes', 'No — sinking fund'], ['TV on sale', 'No', 'No', 'No', 'No'], ['Emergency dental work', 'Yes', 'Yes', 'Yes', 'Yes'], ['Phone screen cracked; upgrade wanted', 'Yes', 'Partly', 'Partly', 'Repair only']],
        takeaway: 'The grey case is handled by funding the minimum need — the repair — not the upgrade.',
      },
      mistakes: ['No written definition', 'Using the fund for predictable bills', 'Funding an upgrade instead of the minimum need'],
      exercise: 'Write three things that count as an emergency in your household.',
      apply: [{ href: '/academy/sinking-funds', label: 'Lesson: sinking funds', d: 'Where predictable costs belong.' }],
    },
    check: {
      questions: [
        Q('Which is an emergency?', ['A planned holiday', 'Urgent medical bill', 'A sale', 'Annual premium'], 1, 'Unexpected, necessary and urgent.'),
        Q('Your annual insurance is due. Where should it come from?', ['Emergency fund', 'A sinking fund', 'A credit card', 'Investments'], 1, 'It is predictable.'),
        Q('Your phone breaks and you want a better model. The fund should pay for…', ['The best model', 'The minimum replacement or repair', 'Nothing ever', 'Two phones'], 1, 'Upgrades are paid separately.'),
      ],
      puzzle: { q: 'A $480 repair is a true emergency, but you also want a $150 upgrade at the same time. How much comes from the emergency fund?', answer: '$480', steps: 'Only the minimum need ($480). The $150 upgrade comes from spending money or savings for wants.' },
    },
  },
  {
    slug: 'refill-emergency-fund', title: 'Refilling the emergency fund after you use it', category: 'Saving', readMins: 4, updated: U,
    excerpt: 'Using the fund is what it is for. Rebuilding it fast is what keeps the next surprise from becoming debt.',
    body: [
      'Using your emergency fund for a real emergency is a success, not a failure. The risk comes after: an empty fund means the next surprise lands on a credit card.',
      { h: 'Make the refill the top goal' },
      'Pause lower-priority goals and send that money to the fund until it is back to at least one month of essentials. Keep paying minimums on debts and keep any employer retirement match.',
      { h: 'Use temporary boosts' },
      { list: ['Redirect money from paused goals.', 'Send windfalls — tax refunds, bonuses, sold items — straight to the fund.', 'Trim discretionary spending for a set period, with an end date.'] },
      { h: 'If the emergency added debt' },
      'If part of the emergency went on a card, a common approach is to rebuild a small cushion first, then attack the card. Without a cushion, the next surprise adds to the card again.',
      { h: 'Learn from the event' },
      'Ask whether the emergency was predictable in hindsight — an ageing car, an old appliance. If so, a sinking fund for that item can prevent the next one.',
    ],
    extras: {
      objectives: ['Prioritise rebuilding after a withdrawal', 'Use windfalls and paused goals to refill', 'Balance refilling with emergency debt'],
      ideas: [
        { t: 'Using it is success', d: 'That is the fund’s job.' },
        { t: 'Empty is the risk', d: 'The next surprise becomes debt.' },
        { t: 'Temporary, with an end date', d: 'Short sprints are easier to keep.' },
      ],
      plan: [
        { t: 'Note the new balance', d: 'And the gap to target.' },
        { t: 'Pause lower goals', d: 'Redirect their money.' },
        { t: 'Send windfalls in', d: 'Refunds, bonuses, sales.' },
        { t: 'Restart goals', d: 'When back to target.' },
      ],
      example: {
        title: 'Rebuilding $1,800 after a car repair', intro: 'Illustrative: $200 usual transfer plus $150 from a paused holiday goal and a $400 tax refund in month 2.',
        head: ['Month', 'Added', 'Gap remaining'],
        rows: [['Start', '', '$1,800'], ['1', '$350', '$1,450'], ['2', '$750 (includes $400 refund)', '$700'], ['3', '$350', '$350'], ['4', '$350', '$0']],
        takeaway: 'Four months to rebuild, after which the holiday goal restarts.',
      },
      mistakes: ['Feeling guilty and avoiding the fund', 'Restarting every goal at once', 'Ignoring a predictable cause'],
      exercise: 'If you have used your fund, write the gap to target and how many months your current transfers need to close it.',
      apply: [{ href: '/academy/fund-your-emergency-fund', label: 'Lesson: fund your emergency fund', d: 'Find money already leaking.' }],
    },
    check: {
      questions: [
        Q('After using the fund for a real emergency you should…', ['Feel bad and stop saving', 'Make refilling the top goal', 'Invest the rest', 'Close the account'], 1, 'Rebuild before the next surprise.'),
        Q('What should keep going while refilling?', ['Every goal', 'Minimum debt payments and any employer match', 'Nothing', 'Only fun spending'], 1, 'Protect credit and free money.'),
        Q('Best use of a tax refund while refilling?', ['A new phone', 'Straight into the fund', 'Split across ten goals', 'Leave it in checking'], 1, 'Windfalls close the gap fastest.'),
      ],
      puzzle: { q: 'The gap is $2,000. You can add $250 a month and expect a $500 bonus in month 3. How many months to refill?', answer: '6 months', steps: 'Without the bonus: 6 × $250 = $1,500 + $500 bonus = $2,000 at month 6.' },
    },
  },
  {
    slug: 'cash-and-inflation', title: 'Cash and inflation: what your savings really earn', category: 'Saving', readMins: 5, updated: U,
    excerpt: 'Inflation slowly reduces what cash can buy. That is fine for short-term money — and a reason long-term money needs a different home.',
    body: [
      'Inflation is the general rise in prices over time. When prices rise, each dollar buys a little less. Cash that earns less than inflation loses purchasing power, even though the balance never falls.',
      { h: 'Nominal versus real' },
      'The nominal return is the rate your account pays. The real return is roughly that rate minus inflation. A 4% savings rate with 3% inflation is about a 1% real return; a 0.5% rate with 3% inflation is about −2.5%.',
      { h: 'Why cash still matters' },
      'For emergency funds and short-term goals, stability and access matter more than growth. Losing a little purchasing power is the price of knowing the money is there when you need it.',
      { h: 'Where inflation matters most' },
      'Money you will not need for many years is where inflation does real damage. That is why long-term goals, such as retirement, usually use investments with higher growth potential — and more risk.',
      { h: 'What you can do' },
      'Keep only short-term money in cash, choose a competitive insured savings rate for it, and review the rate yearly.',
    ],
    extras: {
      objectives: ['Explain nominal and real returns', 'Know when holding cash is right', 'See why long-term money needs growth potential'],
      ideas: [
        { t: 'The balance can grow while value shrinks', d: 'Prices rise faster than a low rate.' },
        { t: 'Stability is worth something', d: 'For money you may need soon.' },
        { t: 'Time magnifies inflation', d: 'Small yearly losses add up over decades.' },
      ],
      plan: [
        { t: 'Sort cash by when you need it', d: 'Within a few years or later.' },
        { t: 'Compare your rate with inflation', d: 'Real return estimate.' },
        { t: 'Move idle cash to a better rate', d: 'Insured savings.' },
        { t: 'Review yearly', d: 'Rates and needs change.' },
      ],
      example: {
        title: 'Real return on $10,000 for one year', intro: 'Illustrative 3% inflation; real return approximated as rate minus inflation.',
        head: ['Account rate', 'Interest earned', 'Approx. real return'],
        rows: [['0.5%', '$50', 'about −2.5%'], ['3.0%', '$300', 'about 0%'], ['4.0%', '$400', 'about +1%']],
        takeaway: 'Cash is a safe place for short-term money, not a growth plan.',
      },
      mistakes: ['Keeping long-term money in a near-zero account', 'Investing emergency money for growth', 'Never checking your savings rate'],
      exercise: 'Look up your savings rate and subtract a recent inflation figure to estimate your real return.',
      apply: [{ href: '/academy/high-yield-savings', label: 'Lesson: high-yield savings', d: 'A better home for cash.' }, { href: '/academy/compound-interest', label: 'Lesson: compound interest', d: 'Why time matters.' }],
    },
    check: {
      questions: [
        Q('A real return is roughly…', ['Rate plus inflation', 'Rate minus inflation', 'Rate times two', 'Always zero'], 1, 'It measures purchasing power.'),
        Q('Which money is fine to hold in cash?', ['Retirement in 30 years', 'Emergency fund', 'A child’s college fund at birth', 'All of it'], 1, 'Short-term money needs stability.'),
        Q('A balance that grows 1% while prices rise 3%…', ['Gains value', 'Loses purchasing power', 'Is unchanged', 'Doubles'], 1, 'It buys less each year.'),
      ],
      puzzle: { q: 'Savings pay 2% and inflation is 3.5%. What is the approximate real return?', answer: 'About −1.5%', steps: '2% − 3.5% = −1.5%.' },
    },
  },
]
