// Academy-native lessons: Stocks and the market (10).
// 🔒 EDUCATION ONLY. GetGuac does not recommend stocks or funds. Every example
// uses a made-up company ("Example Co.") and states its inputs. No ticker symbols.

const Q = (q, options, answer, why) => ({ q, options, answer, why })
const U = '2026-10-01'
const NOTE = 'Education only — GetGuac does not recommend individual stocks.'

export const STOCK_LESSONS = [
  {
    slug: 'what-is-a-stock', title: 'What a stock actually is', category: 'Investing', readMins: 5, updated: U,
    excerpt: 'A share is a small piece of ownership in a company — with a claim on its future profits and its risks.',
    body: [
      'A stock, or share, is a unit of ownership in a company. Owning one share of a company with a million shares means you own one-millionth of it — a claim on a slice of its future profits and, if it fails, a share of the loss.',
      { h: 'How shareholders can benefit' },
      { list: ['Price growth: if the company becomes more valuable, its shares may rise.', 'Dividends: some companies pay part of their profits to shareholders.'] },
      { h: 'The risks' },
      'Share prices move with company results, interest rates, the economy and investor mood. A single company can fall sharply or fail entirely; shareholders are paid last if a company is wound up.',
      { h: 'Why companies sell shares' },
      'Selling shares raises money without borrowing. In exchange, the company gives up part of its ownership and future profits.',
      { h: 'How this fits a plan' },
      'Individual stocks concentrate risk in a few companies. Many long-term investors hold broad funds instead, which spread money across hundreds or thousands of companies. This lesson explains how stocks work so the rest of the track makes sense. ' + NOTE,
    ],
    extras: {
      objectives: ['Explain what owning a share means', 'Name the two ways shareholders can benefit', 'Understand single-company risk'],
      ideas: [
        { t: 'A share is ownership', d: 'Not a loan to the company.' },
        { t: 'Returns are not promised', d: 'Profits and prices can fall.' },
        { t: 'Concentration is risk', d: 'One company can fail.' },
      ],
      plan: [
        { t: 'Learn the vocabulary', d: 'Share, dividend, market value.' },
        { t: 'See your existing exposure', d: 'Retirement funds often own stocks already.' },
        { t: 'Compare single stocks with funds', d: 'Concentration versus spread.' },
        { t: 'Decide your approach', d: 'With a professional if unsure.' },
      ],
      example: {
        title: 'Ownership in numbers', intro: 'Made-up Example Co. with 10,000,000 shares.',
        head: ['You own', 'Ownership share', 'Your slice of $5,000,000 profit'],
        rows: [['100 shares', '0.001%', '$50'], ['1,000 shares', '0.01%', '$500'], ['10,000 shares', '0.1%', '$5,000']],
        takeaway: 'Your slice of profit is not paid to you unless the company pays a dividend; it may instead be reinvested in the business.',
      },
      mistakes: ['Treating a stock like a savings account', 'Putting a large share of savings in one company', 'Investing money needed soon'],
      exercise: 'Check whether your workplace retirement plan already holds stocks through a fund.',
      apply: [{ href: '/academy/index-funds', label: 'Lesson: index funds', d: 'Owning many companies at once.' }],
    },
    check: {
      questions: [
        Q('A share represents…', ['A loan to the company', 'Part ownership of the company', 'A guaranteed return', 'A savings account'], 1, 'Shareholders own a slice of the company.'),
        Q('Two ways shareholders can benefit are…', ['Interest and fees', 'Price growth and dividends', 'Rent and tips', 'Coupons and refunds'], 1, 'Neither is guaranteed.'),
        Q('If a company is wound up, shareholders are paid…', ['First', 'Last', 'Before staff', 'Never asked'], 1, 'Lenders and others are paid before shareholders.'),
      ],
      puzzle: { q: 'A company has 2,000,000 shares. You own 500. What percentage do you own?', answer: '0.025%', steps: '500 ÷ 2,000,000 = 0.00025 = 0.025%.' },
    },
  },
  {
    slug: 'common-vs-preferred-stock', title: 'Common versus preferred stock', category: 'Investing', readMins: 4, updated: U,
    excerpt: 'Common shares usually vote and share in growth; preferred shares usually pay set dividends and get paid first.',
    body: [
      'Companies can issue more than one kind of share. The two main kinds are common and preferred, and they trade off growth against priority.',
      { h: 'Common stock' },
      'Most shares people buy are common stock. Holders usually get voting rights and share in the company’s growth, but dividends are not guaranteed and common holders are paid last.',
      { h: 'Preferred stock' },
      'Preferred shares usually pay a set dividend and are paid before common shareholders — both for dividends and if the company is wound up. They usually do not vote, and their price tends to move less with company growth, behaving partly like a bond.',
      { h: 'Read the terms' },
      { list: ['Cumulative or not: whether missed dividends must be paid later.', 'Callable: whether the company can buy the shares back at a set price.', 'Convertible: whether they can turn into common shares.'] },
      'Terms vary between issues, so the specific prospectus matters. ' + NOTE,
    ],
    extras: {
      objectives: ['Compare common and preferred shares', 'Know what “cumulative” and “callable” mean', 'Understand the growth-versus-priority trade-off'],
      ideas: [
        { t: 'Growth versus priority', d: 'Common for upside, preferred for steadier income.' },
        { t: 'Votes usually go with common', d: 'Preferred holders usually do not vote.' },
        { t: 'Terms differ by issue', d: 'Read the specific prospectus.' },
      ],
      plan: [
        { t: 'Learn the two types', d: 'Rights and priority.' },
        { t: 'Note key terms', d: 'Cumulative, callable, convertible.' },
        { t: 'Compare to bonds', d: 'Preferred behaves partly like one.' },
        { t: 'Read before buying', d: 'Any specific issue.' },
      ],
      example: {
        title: 'Side by side', intro: 'Typical features; individual issues differ.',
        head: ['Feature', 'Common', 'Preferred'],
        rows: [['Voting rights', 'Usually yes', 'Usually no'], ['Dividend', 'Variable, not guaranteed', 'Usually a set rate'], ['Paid first?', 'Last', 'Before common'], ['Share in growth', 'Fully', 'Limited']],
        takeaway: 'Neither is “better” — they suit different goals.',
      },
      mistakes: ['Assuming preferred dividends are guaranteed', 'Ignoring call features', 'Treating preferred as risk-free'],
      exercise: 'Write one sentence explaining the main trade-off between common and preferred shares.',
      apply: [{ href: '/academy/what-is-a-stock', label: 'Lesson: what a stock is', d: 'Start here.' }],
    },
    check: {
      questions: [
        Q('Who is usually paid first?', ['Common shareholders', 'Preferred shareholders', 'Neither', 'Whoever bought last'], 1, 'Preferred has priority over common.'),
        Q('Which usually has voting rights?', ['Common', 'Preferred', 'Both always', 'Neither'], 0, 'Preferred holders usually do not vote.'),
        Q('“Cumulative” preferred means…', ['Missed dividends must be paid later', 'It votes twice', 'It converts automatically', 'It has no dividend'], 0, 'Unpaid dividends accumulate.'),
      ],
      puzzle: { q: 'A preferred share with a $50 par value pays a 6% dividend. What is the yearly dividend?', answer: '$3.00', steps: '$50 × 0.06 = $3.00 a year.' },
    },
  },
  {
    slug: 'how-stock-exchanges-work', title: 'How stock exchanges work', category: 'Investing', readMins: 5, updated: U,
    excerpt: 'Companies raise money once; after that, shares change hands between investors on exchanges.',
    body: [
      'There are two markets for shares. In the primary market, a company sells new shares to raise money — an initial public offering (IPO) is the best-known example. In the secondary market, investors buy and sell existing shares with each other, and the company receives nothing.',
      { h: 'What an exchange does' },
      'An exchange matches buyers and sellers under set rules. Prices move as orders change: more buyers than sellers at a price pushes it up; more sellers pushes it down.',
      { h: 'Bid, ask and spread' },
      'The bid is the highest price a buyer is offering; the ask is the lowest price a seller will accept. The difference is the spread. Busy, widely traded shares usually have small spreads.',
      { h: 'Order types' },
      { list: ['Market order: buy or sell now at the best available price.', 'Limit order: buy or sell only at your price or better; it may not fill.'] },
      { h: 'Brokers' },
      'Individuals reach exchanges through a broker. Check a broker’s fees and confirm it is registered; FINRA BrokerCheck lets you look one up. ' + NOTE,
    ],
    extras: {
      objectives: ['Tell the primary and secondary markets apart', 'Explain bid, ask and spread', 'Choose between market and limit orders'],
      ideas: [
        { t: 'Companies raise money once', d: 'Later trades are between investors.' },
        { t: 'Price is agreement', d: 'Buyers and sellers meeting.' },
        { t: 'Limits protect price', d: 'At the cost of maybe not filling.' },
      ],
      plan: [
        { t: 'Learn the two markets', d: 'Primary and secondary.' },
        { t: 'Read a quote', d: 'Bid, ask, spread.' },
        { t: 'Understand order types', d: 'Market versus limit.' },
        { t: 'Check any broker', d: 'Fees and registration.' },
      ],
      example: {
        title: 'Reading a quote', intro: 'Made-up quote for Example Co.',
        head: ['Field', 'Value', 'Meaning'],
        rows: [['Bid', '$49.95', 'Best buyer price'], ['Ask', '$50.05', 'Best seller price'], ['Spread', '$0.10', 'Ask − bid'], ['Market buy of 100 shares', 'about $5,005', 'Fills near the ask']],
        takeaway: 'A limit buy at $49.95 would cost less if filled — but it might not fill.',
      },
      mistakes: ['Using market orders on thinly traded shares', 'Ignoring the spread as a cost', 'Using an unregistered broker'],
      exercise: 'Look up any widely traded fund’s quote and calculate its spread.',
      apply: [{ href: 'https://brokercheck.finra.org', label: 'FINRA BrokerCheck', d: 'Look up a broker.' }],
    },
    check: {
      questions: [
        Q('When you buy a share on an exchange from another investor, the company receives…', ['The money', 'Nothing', 'Half', 'A fee'], 1, 'That is the secondary market.'),
        Q('The spread is…', ['Ask − bid', 'Bid + ask', 'The dividend', 'A tax'], 0, 'The gap between best seller and best buyer.'),
        Q('A limit order…', ['Always fills', 'Fills only at your price or better', 'Ignores price', 'Is illegal'], 1, 'It may not fill at all.'),
      ],
      puzzle: { q: 'Bid $19.90, ask $20.10. You buy 50 shares at the ask and immediately sell at the bid. What did the spread cost you?', answer: '$10', steps: 'Spread $0.20 × 50 shares = $10.' },
    },
  },
  {
    slug: 'market-capitalization', title: 'Market capitalisation: large, mid and small', category: 'Investing', readMins: 4, updated: U,
    excerpt: 'Market cap is share price × shares outstanding — the market’s price tag for the whole company.',
    body: [
      'Market capitalisation, or market cap, is the total value the market places on a company’s shares: share price multiplied by the number of shares outstanding.',
      { h: 'Size groups' },
      'Investors commonly group companies by size. The exact cut-offs vary by source, but a common convention is large-cap above about $10 billion, mid-cap between about $2 billion and $10 billion, and small-cap below about $2 billion.',
      { h: 'Why size matters' },
      { list: ['Larger companies tend to be more established, with steadier prices.', 'Smaller companies can grow faster but tend to be more volatile.', 'Many index funds are built by size, such as large-cap or small-cap funds.'] },
      { h: 'A high share price is not a big company' },
      'A $500 share can belong to a smaller company than a $50 share. Only price × shares tells you the size.',
      { h: 'Cap-weighted indexes' },
      'Many indexes weight companies by market cap, so the largest companies have the biggest influence on the index. ' + NOTE,
    ],
    extras: {
      objectives: ['Calculate market cap', 'Describe common size groups', 'Explain cap weighting in indexes'],
      ideas: [
        { t: 'Price alone says little', d: 'Shares outstanding matter.' },
        { t: 'Size and volatility', d: 'Smaller companies often swing more.' },
        { t: 'Big companies drive cap-weighted indexes', d: 'Weight follows size.' },
      ],
      plan: [
        { t: 'Learn the formula', d: 'Price × shares outstanding.' },
        { t: 'Learn the common size groups', d: 'Large, mid, small.' },
        { t: 'Check a fund’s size focus', d: 'In its description.' },
        { t: 'Note index weighting', d: 'Cap-weighted or equal-weighted.' },
      ],
      example: {
        title: 'Price versus size', intro: 'Two made-up companies.',
        head: ['Company', 'Share price', 'Shares', 'Market cap'],
        rows: [['Example A', '$500', '4,000,000', '$2,000,000,000'], ['Example B', '$50', '400,000,000', '$20,000,000,000']],
        takeaway: 'The $50 share belongs to the company ten times larger.',
      },
      mistakes: ['Judging size by share price', 'Assuming small companies always grow faster', 'Ignoring how an index is weighted'],
      exercise: 'Calculate the market cap of a made-up company: $25 share price, 80 million shares.',
      apply: [{ href: '/academy/sp-500-explained', label: 'Lesson: the S&P 500', d: 'A cap-weighted index.' }],
    },
    check: {
      questions: [
        Q('Market cap equals…', ['Price × shares outstanding', 'Profit × 10', 'Revenue', 'Dividends × shares'], 0, 'The market’s value for all shares.'),
        Q('Does a higher share price mean a bigger company?', ['Always', 'Not necessarily', 'Never', 'Only in tech'], 1, 'Shares outstanding matter too.'),
        Q('In a cap-weighted index, the most influence comes from…', ['The smallest companies', 'The largest companies', 'Random companies', 'New companies'], 1, 'Weight follows market cap.'),
      ],
      puzzle: { q: 'A company’s shares trade at $25 and it has 80,000,000 shares. What is its market cap, and which common group is it in?', answer: '$2 billion — around the small/mid-cap boundary', steps: '$25 × 80,000,000 = $2,000,000,000. Exact cut-offs vary by source.' },
    },
  },
  {
    slug: 'dividends-and-yield', title: 'Dividends and dividend yield', category: 'Investing', readMins: 5, updated: U,
    excerpt: 'Some companies pay out part of their profit. Yield shows the payout relative to the price — and a very high yield can be a warning.',
    body: [
      'A dividend is a payment a company makes to shareholders, usually from profits. Not all companies pay them; many growing companies reinvest profits instead.',
      { h: 'Dividend yield' },
      'Yield = annual dividend per share ÷ share price. A $2 yearly dividend on a $50 share is a 4% yield.',
      { h: 'Why a high yield can be a warning' },
      'Yield rises when the price falls. A very high yield can mean investors expect the dividend to be cut. Dividends are decided by the company and are never guaranteed.',
      { h: 'Payout ratio' },
      'The payout ratio is dividends ÷ earnings. A company paying out more than it earns cannot do so forever.',
      { h: 'Reinvesting' },
      { list: ['Many accounts let dividends buy more shares automatically.', 'Reinvesting lets dividends compound over time.', 'Outside tax-advantaged accounts, dividends are generally taxable in the year received.'] },
      NOTE,
    ],
    extras: {
      objectives: ['Calculate dividend yield', 'Explain why a very high yield can be risky', 'Understand payout ratio and reinvesting'],
      ideas: [
        { t: 'Yield moves with price', d: 'A falling price raises yield.' },
        { t: 'Dividends are a choice', d: 'Companies can cut them.' },
        { t: 'Reinvesting compounds', d: 'Dividends buying more shares.' },
      ],
      plan: [
        { t: 'Learn the yield formula', d: 'Dividend ÷ price.' },
        { t: 'Check the payout ratio', d: 'Dividends ÷ earnings.' },
        { t: 'Decide on reinvesting', d: 'In your account settings.' },
        { t: 'Know the tax treatment', d: 'For taxable accounts.' },
      ],
      example: {
        title: 'Same dividend, falling price', intro: 'Made-up company paying $2.00 a year.',
        head: ['Share price', 'Annual dividend', 'Yield'],
        rows: [['$50', '$2.00', '4%'], ['$40', '$2.00', '5%'], ['$25', '$2.00', '8%']],
        takeaway: 'The yield doubled because the price halved — which may signal trouble, not a bargain.',
      },
      mistakes: ['Chasing the highest yield', 'Assuming dividends are guaranteed', 'Ignoring the payout ratio'],
      exercise: 'Calculate the yield of a made-up $1.20 dividend on a $30 share.',
      apply: [{ href: '/academy/compound-interest', label: 'Lesson: compound interest', d: 'Why reinvesting matters.' }],
    },
    check: {
      questions: [
        Q('Dividend yield equals…', ['Price ÷ dividend', 'Annual dividend ÷ price', 'Profit ÷ shares', 'Dividend × price'], 1, 'A $2 dividend on $50 is 4%.'),
        Q('A sudden very high yield may mean…', ['Guaranteed income', 'The price fell and a cut is feared', 'Free money', 'Nothing'], 1, 'Yield rises as price falls.'),
        Q('Are dividends guaranteed?', ['Yes', 'No', 'Only monthly', 'Only for large companies'], 1, 'Companies decide and can cut them.'),
      ],
      puzzle: { q: 'A company earns $4 per share and pays $3 in dividends. What is the payout ratio?', answer: '75%', steps: '$3 ÷ $4 = 0.75.' },
    },
  },
  {
    slug: 'price-to-earnings-ratio', title: 'The price-to-earnings (P/E) ratio', category: 'Investing', readMins: 5, updated: U,
    excerpt: 'P/E shows how many dollars investors pay for each dollar of yearly profit. Useful for comparison, never a verdict on its own.',
    body: [
      'The P/E ratio divides the share price by earnings per share (EPS). A $60 share with $3 of yearly EPS has a P/E of 20: investors are paying $20 for each $1 of current yearly profit.',
      { h: 'What it can tell you' },
      'A higher P/E usually means investors expect faster future growth; a lower one can mean lower expectations or more risk. It is most useful when comparing similar companies or a company with its own history.',
      { h: 'Trailing and forward' },
      { list: ['Trailing P/E uses the last 12 months of actual earnings.', 'Forward P/E uses estimated future earnings, which may be wrong.'] },
      { h: 'Limits' },
      'P/E does not work when earnings are negative, can be distorted by one-off gains or losses, and differs naturally between industries. A low P/E is not automatically cheap, and a high one is not automatically expensive.',
      NOTE,
    ],
    extras: {
      objectives: ['Calculate P/E', 'Tell trailing from forward P/E', 'Know the ratio’s limits'],
      ideas: [
        { t: 'Price per dollar of profit', d: 'That is all P/E measures.' },
        { t: 'Compare like with like', d: 'Same industry or same company over time.' },
        { t: 'Forward means forecast', d: 'Estimates can be wrong.' },
      ],
      plan: [
        { t: 'Learn the formula', d: 'Price ÷ EPS.' },
        { t: 'Note trailing or forward', d: 'Every time you see one.' },
        { t: 'Compare within an industry', d: 'Not across.' },
        { t: 'Use alongside other facts', d: 'Never alone.' },
      ],
      example: {
        title: 'Two made-up companies', intro: 'Same industry, trailing earnings.',
        head: ['Company', 'Price', 'EPS', 'P/E'],
        rows: [['Example A', '$60', '$3.00', '20'], ['Example B', '$45', '$1.50', '30']],
        takeaway: 'B’s price is lower but investors pay more for each dollar of its profit.',
      },
      mistakes: ['Calling a low P/E cheap without context', 'Comparing P/E across unrelated industries', 'Treating forward estimates as facts'],
      exercise: 'Calculate the P/E of a made-up $80 share earning $5 per share.',
      apply: [{ href: '/academy/growth-vs-value', label: 'Lesson: growth vs. value', d: 'Where P/E is used.' }],
    },
    check: {
      questions: [
        Q('P/E equals…', ['Price ÷ EPS', 'EPS ÷ price', 'Price × EPS', 'Dividend ÷ price'], 0, 'Dollars paid per dollar of profit.'),
        Q('Forward P/E uses…', ['Past earnings', 'Estimated future earnings', 'Dividends', 'Revenue'], 1, 'Forecasts can be wrong.'),
        Q('When does P/E not work?', ['When earnings are negative', 'On Mondays', 'For large companies', 'Always works'], 0, 'There is no meaningful ratio with losses.'),
      ],
      puzzle: { q: 'A share trades at $80 with EPS of $5. What is the P/E? What price gives a P/E of 12?', answer: 'P/E 16; $60', steps: '$80 ÷ $5 = 16. $5 × 12 = $60.' },
    },
  },
  {
    slug: 'growth-vs-value', title: 'Growth and value investing styles', category: 'Investing', readMins: 5, updated: U,
    excerpt: 'Growth focuses on fast-rising earnings; value on prices that look low against fundamentals. Neither wins every decade.',
    body: [
      'Growth and value are two broad styles of choosing stocks, and many funds are labelled by one or the other.',
      { h: 'Growth' },
      'Growth companies are expected to increase revenue or earnings faster than average. They often reinvest profits instead of paying dividends and tend to have higher P/E ratios, because investors pay for expected future growth.',
      { h: 'Value' },
      'Value companies trade at prices that look low relative to measures such as earnings, book value or cash flow. They are often more established and more likely to pay dividends.',
      { h: 'Neither always wins' },
      'Each style has had long periods of doing better than the other. Many broad index funds hold both, which avoids betting on which style will lead.',
      { h: 'Labels are approximations' },
      { list: ['A company can move between styles as its price and growth change.', 'Index providers use different rules to classify the same company.', 'Check what a “growth” or “value” fund actually holds.'] },
      NOTE,
    ],
    extras: {
      objectives: ['Describe growth and value styles', 'Explain why each has had good and bad periods', 'See why broad funds hold both'],
      ideas: [
        { t: 'Paying for the future versus the present', d: 'Growth versus value.' },
        { t: 'Leadership rotates', d: 'No style wins forever.' },
        { t: 'Broad funds sidestep the bet', d: 'They own both.' },
      ],
      plan: [
        { t: 'Learn both definitions', d: 'Expectations versus price.' },
        { t: 'Check your funds’ style', d: 'In their descriptions.' },
        { t: 'Avoid chasing last year’s winner', d: 'Leadership changes.' },
        { t: 'Consider a broad blend', d: 'If unsure.' },
      ],
      example: {
        title: 'Typical characteristics', intro: 'General tendencies, not rules.',
        head: ['Feature', 'Growth', 'Value'],
        rows: [['P/E ratio', 'Higher', 'Lower'], ['Dividends', 'Often small or none', 'More common'], ['Stage', 'Expanding fast', 'Established'], ['Main risk', 'Growth disappoints', 'Low price is deserved']],
        takeaway: 'Both styles carry risk; they are just different risks.',
      },
      mistakes: ['Switching style after a good year for the other', 'Assuming value means safe', 'Assuming growth means better'],
      exercise: 'Look up whether a fund in your retirement plan is labelled growth, value or blend.',
      apply: [{ href: '/academy/total-market-funds', label: 'Lesson: total market funds', d: 'A blend of both.' }],
    },
    check: {
      questions: [
        Q('Growth companies usually have…', ['Lower P/E ratios', 'Higher P/E ratios', 'No earnings ever', 'Guaranteed returns'], 1, 'Investors pay for expected growth.'),
        Q('Value stocks look cheap relative to…', ['Their logo', 'Fundamentals like earnings', 'Their age', 'Their country'], 1, 'Price versus measures of worth.'),
        Q('Which style always does best?', ['Growth', 'Value', 'Neither — leadership rotates', 'Whichever is newest'], 2, 'Each has had long strong and weak periods.'),
      ],
      puzzle: { q: 'Company A: price $90, EPS $3. Company B: price $40, EPS $4. Which looks more like growth by P/E?', answer: 'A (P/E 30 vs 10)', steps: '$90 ÷ $3 = 30. $40 ÷ $4 = 10. A higher P/E usually signals growth expectations.' },
    },
  },
  {
    slug: 'ipos-explained', title: 'IPOs: how companies go public', category: 'Investing', readMins: 5, updated: U,
    excerpt: 'An initial public offering is a company’s first sale of shares to the public. Early trading can be volatile.',
    body: [
      'An initial public offering (IPO) is when a private company first sells shares to the public and lists them on an exchange. It raises money for the company and lets early owners sell some of their stake.',
      { h: 'How it works' },
      'The company works with investment banks to set a price range, gauge demand from large investors and set a final offer price. Shares then begin trading on the secondary market, where the price can move far from the offer price.',
      { h: 'Why early trading is unpredictable' },
      { list: ['There is little public trading history.', 'Hype can push early prices up, and they can fall back.', 'Insiders are often restricted from selling for a lock-up period, commonly several months; when it ends, more shares may be sold.'] },
      { h: 'Read the prospectus' },
      'Before an IPO, the company files a prospectus with the SEC describing its business, finances and risks. It is long, but the risk-factors section is worth reading.',
      NOTE,
    ],
    extras: {
      objectives: ['Explain what an IPO is', 'Know why early IPO trading is volatile', 'Find the prospectus and risk factors'],
      ideas: [
        { t: 'Offer price is not trading price', d: 'Many individuals buy at the market price.' },
        { t: 'Little history, high uncertainty', d: 'Early prices can swing.' },
        { t: 'Lock-ups end', d: 'Insider selling can follow.' },
      ],
      plan: [
        { t: 'Learn the stages', d: 'Pricing, listing, trading.' },
        { t: 'Find the prospectus', d: 'On the SEC’s EDGAR database.' },
        { t: 'Read the risk factors', d: 'At minimum.' },
        { t: 'Note the lock-up date', d: 'If following a new listing.' },
      ],
      example: {
        title: 'Offer price versus first-day price', intro: 'Made-up IPO: 10,000,000 shares offered at $20.',
        head: ['Item', 'Value'],
        rows: [['Money raised at offer price', '$200,000,000'], ['First trade', '$30 (+50% vs offer)'], ['Buying 10 shares at first trade', '$300'], ['Same 10 shares if price returns to $20', '$200']],
        takeaway: 'Buying at the first trade rather than the offer price can mean starting with a loss if hype fades.',
      },
      mistakes: ['Assuming you will get the offer price', 'Buying on hype alone', 'Skipping the risk factors'],
      exercise: 'Search the SEC’s EDGAR database for any recent prospectus and read its first risk factor.',
      apply: [{ href: 'https://www.sec.gov/edgar/search/', label: 'SEC EDGAR', d: 'Company filings and prospectuses.' }],
    },
    check: {
      questions: [
        Q('An IPO is…', ['A company’s first public sale of shares', 'A dividend', 'A bankruptcy', 'A loan'], 0, 'Private becomes public.'),
        Q('Many individuals buy IPO shares at…', ['The offer price always', 'The market price once trading starts', 'Half price', 'No price'], 1, 'Offer allocations often go to large investors.'),
        Q('A lock-up period restricts…', ['New investors', 'Insiders from selling for a time', 'Exchanges', 'Dividends'], 1, 'When it ends, more shares may be sold.'),
      ],
      puzzle: { q: 'An IPO is priced at $18 and first trades at $27. What is the first-trade percentage gain over the offer price?', answer: '50%', steps: '($27 − $18) ÷ $18 = 0.5.' },
    },
  },
  {
    slug: 'stock-splits-and-dilution', title: 'Stock splits and share dilution', category: 'Investing', readMins: 4, updated: U,
    excerpt: 'A split changes the number of shares, not the value. Dilution is different — it can shrink your ownership share.',
    body: [
      'A stock split divides each share into more shares. In a 2-for-1 split, one $100 share becomes two $50 shares. Your total value does not change; only the number of shares and the price per share do.',
      { h: 'Why companies split' },
      'A lower share price can make shares easier to trade in round numbers. A split does not change the company’s value or profits.',
      { h: 'Reverse splits' },
      'A reverse split combines shares — for example 1-for-10 — raising the price per share. It also does not change total value, though it is sometimes used when a price has fallen very low.',
      { h: 'Dilution' },
      'Dilution happens when a company issues new shares — to raise money, pay employees or buy another company. Your share count stays the same while the total grows, so your percentage of ownership falls.',
      { h: 'Why dilution matters' },
      { list: ['Profit is spread over more shares, lowering earnings per share unless profit grows.', 'Whether it hurts depends on what the new money achieves.'] },
      NOTE,
    ],
    extras: {
      objectives: ['Calculate shares and price after a split', 'Tell a split from dilution', 'Explain how dilution affects ownership and EPS'],
      ideas: [
        { t: 'Splits change slices, not the pie', d: 'Total value is unchanged.' },
        { t: 'Dilution adds slices', d: 'Your share of the pie shrinks.' },
        { t: 'Use of money matters', d: 'Dilution can still be worth it.' },
      ],
      plan: [
        { t: 'Learn split maths', d: 'Shares × ratio, price ÷ ratio.' },
        { t: 'Learn dilution maths', d: 'Your shares ÷ new total.' },
        { t: 'Watch share count', d: 'In company reports.' },
        { t: 'Ask what new money funds', d: 'Growth or survival.' },
      ],
      example: {
        title: 'Split versus dilution', intro: 'Made-up company with 1,000,000 shares; you own 10,000 worth $100 each.',
        head: ['Event', 'Your shares', 'Total shares', 'Your ownership', 'Your value'],
        rows: [['Before', '10,000', '1,000,000', '1.0%', '$1,000,000'], ['After 2-for-1 split', '20,000', '2,000,000', '1.0%', '$1,000,000'], ['After issuing 250,000 new shares (no split)', '10,000', '1,250,000', '0.8%', 'Depends on price']],
        takeaway: 'The split left ownership at 1%; dilution cut it to 0.8%.',
      },
      mistakes: ['Thinking a split makes you richer', 'Ignoring rising share counts', 'Assuming all dilution is bad'],
      exercise: 'Work out your shares and price after a 3-for-1 split of 30 shares at $150.',
      apply: [{ href: '/academy/what-is-a-stock', label: 'Lesson: what a stock is', d: 'Ownership basics.' }],
    },
    check: {
      questions: [
        Q('After a 2-for-1 split your total value…', ['Doubles', 'Halves', 'Stays the same', 'Disappears'], 2, 'More shares at a lower price.'),
        Q('Dilution happens when…', ['A company issues new shares', 'Shares split', 'Dividends are paid', 'Prices fall'], 0, 'Your percentage of ownership falls.'),
        Q('A 1-for-10 reverse split…', ['Raises price per share, same total value', 'Lowers price', 'Doubles value', 'Pays a dividend'], 0, 'Fewer, pricier shares.'),
      ],
      puzzle: { q: 'You own 30 shares at $150. After a 3-for-1 split, how many shares and at what price?', answer: '90 shares at $50', steps: '30 × 3 = 90. $150 ÷ 3 = $50. Value stays $4,500.' },
    },
  },
  {
    slug: 'bull-and-bear-markets', title: 'Bull and bear markets', category: 'Investing', readMins: 5, updated: U,
    excerpt: 'Markets rise and fall in cycles. A plan made before the fall is the one that survives it.',
    body: [
      'A bull market is a sustained rise in prices; a bear market is a sustained fall. A common definition of a bear market is a decline of 20% or more from a recent high, and a correction is often described as a fall of about 10%.',
      { h: 'Declines are normal' },
      'Broad stock markets have historically experienced corrections and bear markets regularly, and have also recovered from them over time — though recoveries have taken anywhere from months to years, and past patterns do not guarantee the future.',
      { h: 'Why timing is hard' },
      'Some of the strongest days have historically come close to some of the worst. Selling after a fall and waiting to feel safe can mean missing the recovery.',
      { h: 'A plan for the next fall' },
      { list: ['Keep money needed within a few years out of stocks.', 'Hold an emergency fund so you never have to sell in a downturn.', 'Keep investing on a schedule; regular purchases buy more shares at lower prices.', 'Rebalance back to your chosen mix.'] },
      NOTE,
    ],
    extras: {
      objectives: ['Define bull, bear and correction', 'Understand why timing the market is hard', 'Write a plan for the next decline'],
      ideas: [
        { t: 'Falls are part of investing', d: 'Not a sign the plan failed.' },
        { t: 'Recovery days cluster near bad days', d: 'Timing is hard.' },
        { t: 'Cash prevents forced selling', d: 'An emergency fund protects investments.' },
      ],
      plan: [
        { t: 'Separate short-term money', d: 'Out of stocks.' },
        { t: 'Confirm your emergency fund', d: 'Months of essentials.' },
        { t: 'Automate contributions', d: 'Keep buying.' },
        { t: 'Write your rebalancing rule', d: 'Before the fall.' },
      ],
      example: {
        title: 'A fall and a recovery, in percentages', intro: 'Illustrative arithmetic on a $10,000 portfolio.',
        head: ['Step', 'Change', 'Value'],
        rows: [['Start', '', '$10,000'], ['Bear market', '−25%', '$7,500'], ['Recovery needed to get back', '+33.3%', '$10,000']],
        takeaway: 'A 25% fall needs a 33.3% rise to recover — one reason selling at the bottom locks in the hardest part.',
      },
      mistakes: ['Selling after a fall and waiting to feel safe', 'Investing emergency money', 'Stopping contributions in a downturn'],
      exercise: 'Write one sentence describing what you will do the next time markets fall 20%.',
      apply: [{ href: '/academy/dollar-cost-averaging', label: 'Lesson: dollar-cost averaging', d: 'Keep buying through dips.' }],
    },
    check: {
      questions: [
        Q('A common definition of a bear market is a fall of…', ['5%', '10%', '20% or more from a recent high', '50%'], 2, 'A correction is often about 10%.'),
        Q('Why is timing the market hard?', ['Markets are closed', 'Strong days often come near weak days', 'It is illegal', 'Brokers forbid it'], 1, 'Missing the recovery is costly.'),
        Q('What protects you from selling in a downturn?', ['More stocks', 'An emergency fund', 'A bigger loan', 'Checking prices daily'], 1, 'Cash covers surprises instead.'),
      ],
      puzzle: { q: 'A portfolio falls 40%. What percentage gain is needed to get back to where it started?', answer: 'About 66.7%', steps: '$100 → $60. $60 × (1 + x) = $100, so x = 40 ÷ 60 ≈ 0.667.' },
    },
  },
]
