import Link from 'next/link'
import ToolIcon from './ToolIcon'
import { ArrowLeft, ArrowRight } from 'lucide-react'
import MarketingShell from './MarketingShell'
import MarketingHero from './MarketingHero'
import ConversionBand from './ConversionBand'
import ZoomableImage from '../app/get-started/ZoomableImage'

function Diagram({steps,color}){return <div className="grid min-h-[340px] place-items-center rounded-3xl bg-slate-50 p-6"><ol className="grid w-full gap-4 sm:grid-cols-3">{steps.map(([verb,value],index)=><li key={verb} className="rounded-2xl border border-slate-200 bg-white p-5 text-center shadow-sm"><span className="mx-auto grid size-10 place-items-center rounded-full text-sm font-black text-white" style={{backgroundColor:color}}><ToolIcon label={`${verb} ${value}`} size={21}/></span><strong className="mt-3 block text-lg text-slate-950">{verb}</strong><span className="mt-1 block text-sm text-slate-600">{value}</span></li>)}</ol></div>}

export default function FeatureDetailPage({group,detail}){return <MarketingShell subtitle={detail.name.toLowerCase()}><MarketingHero eyebrow={detail.eyebrow} title={detail.title} description={detail.summary} primaryHref={detail.actionHref} primaryLabel={detail.action} secondaryHref={`/features/${group.slug}`} secondaryLabel={`All ${group.name.toLowerCase()} tools`} imageSrc={group.photo} imageAlt={group.photoAlt}/><section className="mx-auto max-w-6xl py-10 sm:py-14"><div className="grid items-center gap-7 rounded-[28px] p-5 sm:p-8 lg:grid-cols-[.62fr_1.38fr]" style={{backgroundColor:`${group.color}0d`}}><div><p className="text-xs font-bold uppercase tracking-[.16em]" style={{color:group.color}}>How it fits</p><h2 className="mt-3 text-3xl font-black text-slate-950">One focused tool. One clear next step.</h2>{detail.screen && detail.steps ? <ul className="mt-4 space-y-3">{detail.steps.map(([label,text])=><li key={label} className="flex items-start gap-3 text-sm leading-6 text-slate-600"><ToolIcon label={`${label} ${text}`} size={21} className="mt-0.5" style={{color:group.color}}/><span><strong className="block text-slate-900">{label}</strong>{text}</span></li>)}</ul> : <p className="mt-4 leading-7 text-slate-600">{detail.summary}</p>}<Link href={detail.actionHref} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-full px-5 text-sm font-bold text-white" style={{backgroundColor:group.color}}>{detail.action}<ArrowRight size={16}/></Link></div><div className="min-w-0 overflow-hidden rounded-3xl border border-slate-200 bg-white">{detail.screen?<ZoomableImage {...detail.screen} imageClassName="block h-auto w-full object-contain" className="rounded-none"/>:<Diagram steps={detail.steps} color={group.color}/>}</div></div><Link href={`/features/${group.slug}`} className="mt-6 inline-flex min-h-11 items-center gap-2 text-sm font-bold" style={{color:group.color}}><ArrowLeft size={16}/>All {group.name.toLowerCase()} tools</Link></section><ConversionBand/></MarketingShell>}

