'use client'
import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import ToolIcon from './ToolIcon'
import { Menu, X, ChevronDown } from 'lucide-react'
import { GG_NAV, GG_CTA } from '../lib/gg-nav-def'
export default function MarketingMobileMenu(){
 const [open,setOpen]=useState(false);const trigger=useRef(null)
 useEffect(()=>{if(!open)return;const close=event=>{if(event.key==='Escape'){setOpen(false);trigger.current?.focus()}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[open])
 return <div className="lg:hidden"><button ref={trigger} type="button" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} aria-controls="marketing-mobile-nav" onClick={()=>setOpen(!open)} className="grid h-11 w-11 place-items-center rounded-lg text-emerald-800">{open?<X size={22}/>:<Menu size={22}/>}</button>{open&&<><button type="button" aria-label="Close navigation backdrop" tabIndex={-1} onClick={()=>setOpen(false)} className="fixed inset-0 top-16 z-40 bg-black/20"/><nav id="marketing-mobile-nav" aria-label="Mobile website navigation" className="fixed inset-x-0 top-16 z-50 max-h-[75vh] overflow-y-auto border-b border-slate-200 bg-white px-5 py-3 shadow-lg">{GG_NAV.filter(n=>n.children).map(n=><details key={n.href} className="group border-b border-slate-100"><summary className="flex min-h-12 cursor-pointer items-center justify-between gap-2 py-3 font-bold text-slate-900"><span className="flex items-center gap-3"><ToolIcon label={n.label} className="text-violet-700"/>{n.label}</span><ChevronDown size={17} className="group-open:rotate-180"/></summary><div className="pb-3 pl-3">{n.children.map(child=><Link key={child.href} href={child.href} onClick={()=>setOpen(false)} className="flex min-h-11 items-center gap-3 rounded-xl px-2 py-2 hover:bg-violet-50 text-sm font-semibold text-slate-600"><ToolIcon label={child.label} size={18} className="text-violet-700"/>{child.label}</Link>)}</div></details>)}<div className="flex flex-wrap gap-3 py-4"><Link href="/login" onClick={()=>setOpen(false)} className="btn-secondary">Sign in</Link><Link href={GG_CTA.href} onClick={()=>setOpen(false)} className="btn-primary">{GG_CTA.label}</Link></div></nav></>}</div>
}
