'use client'

import { CalendarDays, Landmark, TrendingUp, Users, RotateCcw, Store, Tags, Target } from 'lucide-react'
import WorkflowCycle from './WorkflowCycle'

const STAGES=[
 {id:'retirement',label:'Retirement',Icon:Landmark,kicker:'Plan beyond this month',title:'Give your future a clearer plan.',text:'Explore how your savings, contributions and timeframe affect a retirement scenario.',href:'/calculators',action:'Explore calculators',diagram:[['Start','Current savings'],['Explore','Time + contributions'],['Review','Your assumptions']]},
 {id:'wealth',label:'Wealth',Icon:TrendingUp,kicker:'See your position',title:'Keep the bigger picture in view.',text:'Review your assets, debt and net worth together in Wealth Path.',href:'/goals/money-goals.html',action:'Read the goals guide',diagram:[['Record','Assets'],['Review','Debts'],['See','Net worth']]},
 {id:'family',label:'Family',Icon:Users,kicker:'Plan together',title:'Keep your household connected.',text:'Manage household connections and choose the sharing controls that work for your family.',href:'/connections',action:'Explore family connections',diagram:[['Connect','Your household'],['Choose','What to share'],['Review','Access together']]},
 {id:'goals',label:'Goals',Icon:Target,kicker:'Name what matters',title:'Give the future a target.',text:'Set the purpose, amount and timeframe, then record progress without pretending GetGuac moves the money.',href:'/goals/money-goals.html',action:'Read the goals guide',diagram:[['Choose','Purpose + target'],['Record','Saved progress'],['Review','Pace + next step']]},
 {id:'bills',label:'Bills',Icon:CalendarDays,kicker:'Protect the month',title:'See recurring costs before they surprise you.',text:'Keep due dates and subscriptions visible while deciding what still belongs in the plan.',href:'/features/prepare',action:'Explore bill tracking',screen:{src:'/marketing/current/bills.webp',width:1440,height:900,alt:'GetGuac bills calendar showing recurring costs and due dates'}},
 {id:'returns',label:'Returns',Icon:RotateCcw,kicker:'Recover value after checkout',title:'Keep the deadline in sight.',text:'See return windows, refundable amounts and refund status beside the purchase record.',href:'/goals/recover.html',action:'Track returns',screen:{src:'/marketing/current/returns.webp',width:1440,height:900,alt:'GetGuac returns screen showing purchase return deadlines and status'}},
 {id:'deals',label:'Deals',Icon:Tags,kicker:'Shop from the plan',title:'Compare offers without confusing them with purchases.',text:'Review promotions for things already on your list while keeping marketing messages separate from receipts.',href:'/deals',action:'Explore deals',screen:{src:'/marketing/current/steals.webp',width:1148,height:718,alt:'GetGuac Steals screen showing shopping offers separately from purchase records'}},
 {id:'market',label:'Market',Icon:Store,kicker:'Compare before checkout',title:'Find a price worth comparing.',text:'Search products and compare retailer offers for something you already plan to buy.',href:'/marketplace',action:'Open Marketplace',screen:{src:'/marketing/current/marketplace.webp',width:1440,height:900,alt:'GetGuac Marketplace screen showing retailer products and price comparisons'}},
]

export default function ProtectCycle(){return <WorkflowCycle ariaLabel="Protect workflow stages" eyebrow="The Protect cycle" title="Plan it. Keep it. Recover it." intro="Every protected purchase can strengthen the next goal." returnText="Return to the goal with more value protected." stages={STAGES} accent="#6d28d9" soft="#f5f1ff" footnote="GetGuac keeps the supporting record visible. You remain in control of every action."/>}
