'use client'

import { BookOpen, Calculator, Gauge, LayoutDashboard, PieChart, Star, Wallet } from 'lucide-react'
import WorkflowCycle from './WorkflowCycle'

const STAGES=[
 {id:'dashboard',label:'Dashboard',Icon:LayoutDashboard,kicker:'See today first',title:'Your money briefing, in one place.',text:'Bring activity, reminders and the signals that need attention into one useful starting view.',href:'/dashboard',action:'Open Dashboard',screen:{src:'/marketing/current/dashboard.webp',width:1148,height:718,alt:'GetGuac Dashboard showing spending, budget, cash flow and money indicators'}},
 {id:'budget',label:'Budget',Icon:Wallet,kicker:'Give the month a job',title:'Plan, compare, adjust.',text:'Start with income and expected costs, then compare the plan with the records you add.',href:'/goals/first-budget.html',action:'Read the budget guide',screen:{src:'/marketing/current/budget.webp',width:1440,height:900,alt:'GetGuac Budget showing income sources, monthly spending and remaining money with demo data'}},
 {id:'reports',label:'Reports',Icon:PieChart,kicker:'See what shaped the total',title:'Items become patterns.',text:'Move from one store total to categories, time periods and the purchases behind each result.',href:'/reports',action:'Open Reports',screen:{src:'/marketing/current/reports.webp',width:1440,height:900,alt:'GetGuac spending-by-category report with amounts and proportional bars'}},
 {id:'scores',label:'Indicators',Icon:Gauge,kicker:'Know what needs attention',title:'Signals with evidence behind them.',text:'Use GuacScore and GuacWizard as starting signals, then open the records that explain them.',href:'/goals/wizard.html',action:'Explore indicators',screen:{src:'/marketing/current/guacwizard.webp',width:1148,height:718,alt:'GetGuac GuacWizard showing fees, interest and the records behind its score'}},
 {id:'worth-it',label:'Worth It',Icon:Star,kicker:'Remember value, not only cost',title:'Teach the next purchase.',text:'Rate purchases and keep a record of what genuinely earned another dollar.',href:'/features/worth-it',action:'Explore Worth It',screen:{src:'/marketing/current/worth-it.webp',width:1148,height:718,alt:'GetGuac Worth It screen showing purchase ratings and spending context'}},
 {id:'calculators',label:'Calculate',Icon:Calculator,kicker:'Explore before deciding',title:'Test a money scenario.',text:'Change your own assumptions and compare savings or debt paths without pretending the result is a guarantee.',href:'/calculators',action:'Use calculators',diagram:[['Choose','A scenario'],['Change','Your assumptions'],['Compare','Possible paths']]},
 {id:'learning',label:'Learn',Icon:BookOpen,kicker:'Turn insight into confidence',title:'Learn the next useful thing.',text:'Use practical guides, current context and activities when a money question needs more than a number.',href:'/learn',action:'Explore learning',diagram:[['Notice','A question'],['Learn','Plain-language context'],['Use','One practical next step']]},
]

export default function UnderstandCycle(){return <WorkflowCycle ariaLabel="Understand workflow stages" eyebrow="The Understand cycle" title="See it. Plan it. Learn from it." intro="Each answer leads back to a clearer dashboard." returnText="Return to the dashboard with a clearer question." stages={STAGES} accent="#1d4ed8" soft="#eef4ff" footnote="GetGuac shows the records behind an insight. You decide what to do next."/>}
